feat: Introduce ERC6909 token and a corresponding factory for it
centrifuge/protocol-v3 pull request #12
Opened 2024-10-11 22:19 UTC by peculiarity

Implemented the following [feature](https://github.com/centrifuge/asset-pools/issues/3)

2024-10-14 07:54 UTC, hieronx reviewed
Nice start!

One comment already: I would suggest merging `ERC6909`, `ERC6909URI` and `ERC6909Metadata`. Imo the high level of inheritance creates a lot of complexity and makes it hard to understand the full contract. It logically is also okay since all these contracts are part of ERC6909 (just some are optional extensions).

2024-10-15 03:42 UTC, lemunozm reviewed
A review mostly to familiarize myself with these contracts 😃. Some questions and one comment.

2024-10-15 03:42 UTC, lemunozm commented on src/ERC6909.sol
> +            if (allowed != type(uint256).max) allowance[sender][msg.sender][id] = allowed - amount;
I'm curious why the `max` value is treated differently.

2024-10-15 03:42 UTC, lemunozm commented on src/ERC6909.sol
> +    }
If the method is supposed to return `true/false` values. Does it mean that it needs to be infallible? It means, should we check the `sender` has enough amount and return `false` instead of panicking in the subtraction?

2024-10-15 03:42 UTC, lemunozm commented on src/ERC6909Metadata.sol
> +        require(_decimals > 0, MissingDecimals(_tokenId));
Why this requirement? Could I not have a token with no decimals?

2024-10-15 07:30 UTC, wischli reviewed
A few silly questions from my side

2024-10-15 07:30 UTC, wischli commented on src/ERC6909.sol
> +        emit Approval(msg.sender, spender, id, amount);
Q: Do we want to auch events even if the same storage value has already existed?

2024-10-15 07:30 UTC, wischli commented on src/ERC6909Collateral.sol
> +        if (!_baseURI.isEmpty()) {
Q: Would it actually increase gas cost if we did a write operation from an empty to an empty string?

2024-10-15 07:30 UTC, wischli commented on src/ERC6909Collateral.sol
> +    function _burn(address sender, uint256 tokenId, uint256 amount) external auth {
Q: Why is there an external `mint` but no external `burn`?

2024-10-15 07:30 UTC, wischli commented on src/libraries/StringLib.sol
> +    function toString(uint256 value) internal pure returns (string memory) {
Curious if this was taken from somewhere.

2024-10-15 14:42 UTC, peculiarity commented on src/libraries/StringLib.sol
> +    function toString(uint256 value) internal pure returns (string memory) {
This actually a piece of code from our liquidity-pools repository. It was actually an internal or private method for some test file. I've decided to use it and put it into a library.

2024-10-15 14:45 UTC, peculiarity commented on src/ERC6909Metadata.sol
> +        require(_decimals > 0, MissingDecimals(_tokenId));
Actually this is something that was also brought during out audit of liquidity-pools. There are all kind of weird tokens and etc but there is no token in the wild that has no decimals. The least decimals of a known token is 2.

Actually I think it might be a good idea to change it to `>=2` probably. @hieronx  Thoughts?

I just realized that the name of the method is wrong. :)

2024-10-15 14:46 UTC, peculiarity commented on src/ERC6909Collateral.sol
> +    function _burn(address sender, uint256 tokenId, uint256 amount) external auth {
Actually the burn is `external`. If you can see the visibility modifier, it is external. The name is wrong. It should be `burn` instead of `_burn`. Good catch!

2024-10-15 14:46 UTC, hieronx commented on src/ERC6909Metadata.sol
> +        require(_decimals > 0, MissingDecimals(_tokenId));
I wonder if we even need to make it an option here or can just hardcode it to 18. Given that this is really 1 implementation of ERC6909, that we will use for collateral used only in Centrifuge pools.

2024-10-15 14:51 UTC, peculiarity commented on src/ERC6909Collateral.sol
> +        if (!_baseURI.isEmpty()) {
I have to find an article about all the cases but in general it costs more gas.  BTW this is not relevant. We decided that it's going to be removed

2024-10-15 15:23 UTC, peculiarity commented on src/ERC6909.sol
> +    }
I wouldn't say it's panicking. There is no such thing as panicking :D.
It will revert and according to the spec it's fine to revert if the user doesn't have enough balance of a given token. Instead of adding additional check and gas cost the the transaction call, we rely on the execution runtime environment to that for us. I think it's a nice elegant way to achieve the same thing.

This is the way it is used in Uniswap v4.

2024-10-15 15:52 UTC, peculiarity commented on src/ERC6909.sol
> +        emit Approval(msg.sender, spender, id, amount);
Probably it's a nice idea to check for the amount and only update it if it's different value and then fire an event. 
@hieronx  thoughts

2024-10-15 15:57 UTC, peculiarity commented on src/ERC6909Metadata.sol
> +        require(_decimals > 0, MissingDecimals(_tokenId));
This is metadata for the "collateral" type, right? So if these are made out of a single item, do we even need that? Do we plan on supporting something that might require any decimals :S ?

2024-10-15 18:19 UTC, hieronx commented on src/ERC6909.sol
> +        emit Approval(msg.sender, spender, id, amount);
Not sure if there's a good reason for this, but always emitting an event is how every ERC20 implementation I've seen does it, so I'd stay consistent with that.

2024-10-16 09:58 UTC, lemunozm commented on src/ERC6909Metadata.sol
> +        require(_decimals > 0, MissingDecimals(_tokenId));
If we represent non-fungible tokens using this contract, i.e. a house. What's the meaning of having/forcing decimals for such representation?

> This is metadata for the "collateral" type, right?

Yes

> So if these are made out of a single item, do we even need that? Do we plan on supporting something that might require any decimals :S ?

Good questions, also interested on 👀. AFAIK, they can only be a single item. Even if they later have a quantity associated

2024-10-16 10:01 UTC, lemunozm commented on src/ERC6909.sol
> +    }
> I wouldn't say it's panicking. There is no such thing as panicking :D.

Inherent name from Rust :P

Ok, then what will happen if the method that calls this wants to still follow the transaction and perform another action if the `the sender` has not have enough funds?

I guess they are forced to check the balance first, right?

2024-10-16 10:02 UTC, lemunozm commented on src/ERC6909.sol
> +    }
What's the purpose of the interface to allow return a boolean then?

2024-10-16 10:04 UTC, hieronx commented on src/ERC6909Metadata.sol
> +        require(_decimals > 0, MissingDecimals(_tokenId));
Yeah this brings another discussion we need to still have.  Since ERC6909 is effectively a single interface for supporting both fungible and nonfungible tokens, we could potentially actually use the amount of the collateral to represent the quantity. So for T-bills, you would mint 100 tokens if you wanted to buy 100 T-bills.

2024-10-16 10:29 UTC, lemunozm commented on src/ERC6909Metadata.sol
> +        require(_decimals > 0, MissingDecimals(_tokenId));
That sounds pretty interesting! Probably, we could, and it makes more sense

2024-10-16 11:00 UTC, peculiarity commented on src/ERC6909.sol
> +    }
To answer your first question. I think there are 2 solutions.
1. The one you mentioned is to check the the balance beforehand and decide based on that.
2. This one is calling the method within a try / catch statement so if it reverts , you can decide what to do next.

To answer your questions - I have 0 idea. According to the specification it must return true. If we want to be standard compliant, we have to do it. Probably in some cases ( different than lack of balance ), you want to return false. Such an example is if you have some sort of a restriction. It really depends how you implement 6909 and for what reason. In our case, for now, there is no reason to return false but we are still standard compliant.

2024-10-16 11:02 UTC, peculiarity commented on src/ERC6909Metadata.sol
> +        require(_decimals > 0, MissingDecimals(_tokenId));
But why not use just number 100 and not 100*10**(some decimal) ?

2024-10-16 11:18 UTC, lemunozm commented on src/ERC6909.sol
> +    }
Ok, thanks for the well detailed description!!

2024-10-16 11:20 UTC, lemunozm commented on src/ERC6909Metadata.sol
> +        require(_decimals > 0, MissingDecimals(_tokenId));
If we want to use this amount as `quantity` in the future, then we need to use decimals, because you can increase/decrease the debt of portions of such item.

Extreme example: I want to repay half the principal of my mortgage so I can repay 0.5 units of the house.

If we do not go with using this amount as `quantity`, then I do not see the need for decimals.

2024-10-16 19:00 UTC, hieronx commented on src/ERC6909.sol
> +            if (allowed != type(uint256).max) allowance[sender][msg.sender][id] = allowed - amount;
Just a gas optimization that some ERC20 implementations introduced. Assumption is that if the allowance is once set to max uint256, it cannot never become so small that it can block a transfer. It is basically infinitely large.

2024-10-18 08:10 UTC, peculiarity commented on src/ERC6909Metadata.sol
> +        require(_decimals > 0, MissingDecimals(_tokenId));
Actually you repay 0.5 of your mortgage. This amount corresponds to the item. 1 house is always 1 house. 
I think the math logic you are describing is some accounting that has the house as collateral and has some debt drawn for that. So you manage the amount ( increase, decrease ) on that number, not on the item itself.

This is just an assumption only of course.

2024-10-18 08:57 UTC, lemunozm commented on src/ERC6909Metadata.sol
> +        require(_decimals > 0, MissingDecimals(_tokenId));
Correct, the point is that we can use the same representation (same decimals) for both, the collateral and the item against that collateral.

So if my collateral is 1 (house), then in the item, I can take fractions of that 1 with the same representation as ERC6909 says.

Also, I think it's possible to collateralize part of a collateral value in some cases, so in those cases can make sense to deal with "decimals" at that level.

2024-10-21 09:10 UTC, lemunozm commented on src/ERC6909Metadata.sol
> +    function _setSymbol(uint256 _tokenId, uint8 _decimals) internal virtual auth {
I think this name should be `_setDecimals()`  instead

2024-10-22 18:23 UTC, lemunozm commented on src/ERC6909Metadata.sol
> +        require(_decimals > 0, MissingDecimals(_tokenId));
From my point of view, I think we can close this thread with the current implementation, and iterate from here

2024-10-22 18:26 UTC, lemunozm commented on src/interfaces/ERC6909/IERC6909MetadataExtension.sol
> +interface IERC6909MetadataExtension {
Why is this not inherited from `IERC6909` or vice versa?

What happen if I need methods from `IERC6909` and `IERC6909MetadataExtension`? Should I do:

```solidity
interface MyInterface is IERC6909, IERC6909MetadataExtension {}
```
And use `MyInterface` from that point?

2024-10-22 18:35 UTC, lemunozm reviewed
Some comments below, but for me it's almost ready to be merged!

Nice tests!

2024-10-22 18:35 UTC, lemunozm commented on src/Deterministic.sol
> +    function _previewAddress(address deployer, bytes32 salt, bytes memory bytecode)
Agree with this utility.

After some thinking on the name, I think  `getAddress` (from liquidity-pools) represents better this, because if it's deterministic, there is no "preview" or "future" address. It's just an address computed from some parameters. WDYT?

2024-10-22 18:35 UTC, lemunozm commented on src/ERC6909/ERC6909Collateral.sol
> +import "forge-std/Test.sol";
Nit, should be removed.

2024-10-22 18:35 UTC, lemunozm commented on src/ERC6909/ERC6909Errors.sol
> +error ERC6909Collateral_SetDecimal_LessThanMinimalDecimal(uint8 minimal, uint8 actual);
Question: Why the prefixes and why not in the interfaces?

2024-10-22 18:35 UTC, lemunozm commented on src/Deterministic.sol
> +abstract contract Deterministic {
Why is this a contract that should be inherited instead of just a utility function anyone can call?

2024-10-23 05:46 UTC, lemunozm commented on src/ERC6909/ERC6909.sol
> +        balanceOf[sender][id] -= amount;
Just a question. Regarding our `storage` conversation. Could the following be more performant:

```solidity
uint256 storage balance = balanceOf[sender][id];
require(balance >= amount, ERC6909_Transfer_InsufficientBalance(sender, id));

balance -= amount;
```
because we do not need to recompute the access of that storage?

2024-10-23 05:47 UTC, lemunozm commented on src/ERC6909/ERC6909.sol
> +        balanceOf[sender][id] -= amount;
Although anyways I would expect from the compiler optimizer to obtain the same evm code in both cases TBH

2024-10-23 12:44 UTC, peculiarity commented
### ERC6909 Implementation

- When setting up the `symbol`, `name`, `decimals`, do we have to check for an existing token id?
- Do we need an upper bound for the decimals?
- Since this is going to be our first implementation with custom errors, I think we have to agree on some structure of the errors as naming and location. Previously we used something similar to:
`< contract_name > / < error_message >` 
Now the idea is more or less the same. There are some parts of the error name. First contains the contract where it is thrown, the second one is the function and the third one is the actual error. Inspiration is taken from [[here](https://github.com/PaulRBerg/prb-math/blob/main/src/sd1x18/Errors.sol)](https://github.com/PaulRBerg/prb-math/blob/main/src/sd1x18/Errors.sol).
- Do we want to check for empty values when setting up token / contract URIs? Is there a scenario where the URI would be reset to an empty one?
- Currently there is no `totalSupply` for a given `tokenId` implemented. Would we love to have such thing? Currently we can mint *“infinitely”*.
- What happens if the `ERC6909Collateral` is deployed with owner `address(0)`? Do we want to have default owner in `Auth` the `msg.sender` and once the caller verifies that the desired address is part of the wards, then it can delete itself?
- Can we assume that setting `address(0)` is acceptable because we can remove the allowance in a separate transaction?
- Discuss how `totalSupply` must work
    - Increase on mint only
    - Setup the total supply manually at some point of time ( Is this even possible )
- Do we want to allow setting allowance over non-existing `tokenId` ( `tokenId` > `latestTokenId` ?

2024-10-23 14:49 UTC, ilinzweilin requested changes

2024-10-23 14:49 UTC, ilinzweilin commented on src/ERC6909/ERC6909Collateral.sol
> +    /// @inheritdoc IERC6909Collateral
Why do we need to store name, symbol and decimals for each `tokenId`? 
IMO the tokenURI should be enough, since it links to the metadata

2024-10-23 14:49 UTC, ilinzweilin commented on src/ERC6909/ERC6909Collateral.sol
> +    function mint(address _owner, uint256 _tokenId, uint256 _amount) public auth returns (uint256) {
If we agree that the maxSupply of each token in 1, this function is not required.
We would only need to keep it, if we also keep `burn`

2024-10-23 14:49 UTC, ilinzweilin commented on src/ERC6909/ERC6909Collateral.sol
> +        require(_amount > 0, ERC6909Collateral_Mint_EmptyAmount());
If we agree that the maxSupply of each token in 1, we need to make sure that you can never mint more than 1 of each tokenId

2024-10-23 14:49 UTC, ilinzweilin commented on src/ERC6909/ERC6909Collateral.sol
> +        emit Transfer(msg.sender, address(0), _owner, _tokenId, _amount);
why not emit `Mint`

2024-10-23 14:49 UTC, ilinzweilin commented on src/ERC6909/ERC6909Collateral.sol
> +    function burn(address _owner, uint256 _tokenId, uint256 _amount) external auth returns (uint256) {
I wonder if we need `burn` at all.
If we do, I would make it `public` and only the owner of the token can burn.

2024-10-23 15:02 UTC, peculiarity commented on src/ERC6909/ERC6909Collateral.sol
> +    /// @inheritdoc IERC6909Collateral
There has been discussion going on [here](https://github.com/centrifuge/asset-pools/pull/12#discussion_r1800403604).

2024-10-23 15:03 UTC, peculiarity commented on src/ERC6909/ERC6909Collateral.sol
> +    function mint(address _owner, uint256 _tokenId, uint256 _amount) public auth returns (uint256) {
It really depends on whether we want to support fungible assets as well, right ?

2024-10-23 15:07 UTC, peculiarity commented on src/ERC6909/ERC6909Collateral.sol
> +        emit Transfer(msg.sender, address(0), _owner, _tokenId, _amount);
1. We already have the `Transfer` event  defined.
2. According to the reference implementation in the [standard](https://eips.ethereum.org/EIPS/eip-6909#reference-implementation)  the `_mint` method also emits `Transfer` event.
3. If you check the Uniswap V4 [implementation](https://github.com/Uniswap/v4-core/blob/main/src/ERC6909.sol#L37), it also emits `Transfer`

I have the feeling that the consensus is to emit a `Transfer` event with `address(0)` .

2024-10-23 15:08 UTC, peculiarity commented on src/ERC6909/ERC6909Collateral.sol
> +    function burn(address _owner, uint256 _tokenId, uint256 _amount) external auth returns (uint256) {
Why public? Where do we want to call it in a contract? My understanding is that whoever mints, they burn.

2024-10-23 15:10 UTC, ilinzweilin commented on src/ERC6909/ERC6909Collateral.sol
> +    function burn(address _owner, uint256 _tokenId, uint256 _amount) external auth returns (uint256) {
my understanding is whoever owns can burn :)

2024-10-23 15:12 UTC, peculiarity commented on src/ERC6909/ERC6909.sol
> +        balanceOf[sender][id] -= amount;
You can't do that `uint256 storage balance = balanceOf[sender][id];`
You can put `storage` only if it's a complex type .

2024-10-23 15:14 UTC, peculiarity commented on src/ERC6909/ERC6909Errors.sol
> +error ERC6909Collateral_SetDecimal_LessThanMinimalDecimal(uint8 minimal, uint8 actual);
Check 3rd point [here](https://github.com/centrifuge/asset-pools/pull/12#issuecomment-2432032848)

2024-10-23 15:17 UTC, peculiarity commented on src/Deterministic.sol
> +abstract contract Deterministic {
Yeah, no idea. :) Good suggestion.

2024-10-23 15:20 UTC, ilinzweilin commented on src/ERC6909/ERC6909Collateral.sol
> +    /// @inheritdoc IERC6909Collateral
I can not tell from the discussion why the tokens need decimals. Those are still nfts, so I am a bit confused here.

2024-10-23 15:22 UTC, peculiarity commented on src/Deterministic.sol
> +abstract contract Deterministic {
Applied

2024-10-23 15:27 UTC, peculiarity commented on src/Deterministic.sol
> +    function _previewAddress(address deployer, bytes32 salt, bytes memory bytecode)
For me it is preview because it's not actually deploy. You see what it is going to  look like if deployed.
It's like trailer is a preview of a movie. Because you watched the trailer ( which is actually parts of the actual movie ) it doesn't mean you watched the movie. 

It should read more or less smth like : " The address should look like this if you provide these constructor arguments" but that's not the final address. You might want to generate some cool address  so you can test with different `salt` for example.

2024-10-23 15:27 UTC, peculiarity commented on src/interfaces/ERC6909/IERC6909MetadataExtension.sol
> +interface IERC6909MetadataExtension {
Check `IERC6909Collateral` which answers you question I think.

2024-10-23 15:33 UTC, peculiarity commented on src/ERC6909/ERC6909Collateral.sol
> +    /// @inheritdoc IERC6909Collateral
I also have some confusion around that . Also we would like to support fungible tokens ( I think )

2024-10-23 15:35 UTC, peculiarity commented on src/ERC6909/ERC6909Collateral.sol
> +    function burn(address _owner, uint256 _tokenId, uint256 _amount) external auth returns (uint256) {
Actually, yeah It makes sense when you think about it .

2024-10-23 15:42 UTC, peculiarity commented on src/ERC6909/ERC6909Collateral.sol
> +    function burn(address _owner, uint256 _tokenId, uint256 _amount) external auth returns (uint256) {
Applied

2024-10-23 17:16 UTC, ilinzweilin commented on src/ERC6909/ERC6909Collateral.sol
> +    /// @inheritdoc IERC6909Collateral
but even if there are multiple tokens for one tokenID, I don't see why we need that values. 
If @hieronx agrees, I would remove symbol, name and decimals. I don't see how this values would be used.

2024-10-24 05:51 UTC, lemunozm commented on src/ERC6909/ERC6909Collateral.sol
> +            require(totalSupply_ + _amount >= totalSupply_, OverflowUint256(totalSupply_, _amount));
NIT. In theory the error should not be `OverflowUint256` because what we exceed is totalSupply not the max value of `Uint256`.

2024-10-24 05:51 UTC, lemunozm commented on src/Deterministic.sol
> +    function _previewAddress(address deployer, bytes32 salt, bytes memory bytecode)
But you can also call this method to know where a contract was deployed in the past, isn't? I.e. to find an oracle already deployed for some feeder. I mean, it seems like the concept of "time" here depends on how the user uses this method but not on the method itself

2024-10-24 05:51 UTC, lemunozm commented on src/ERC6909/ERC6909Collateral.sol
> +    /// @inheritdoc IERC6909Collateral
I think this comes from a not closed idea of using the amount of tokens as the quantity for the item of the portfolio. So basically if I create an item with quantitiy 100, I could instead create a collateral of 100 tokens associated with that item.

If different tokenIds can have different quantities, they can also have different decimal representations for such quantities.

Nevertheless I think this requires more thought to check if it makes sense. Agree in not going with this yet. Last word to @Jeroen.

2024-10-24 05:51 UTC, lemunozm commented on src/ERC6909/ERC6909Collateral.sol
> +    function mint(address _owner, uint256 _tokenId, uint256 _amount) public auth returns (uint256) {
I also think we wanted to support both kind of tokens

2024-10-24 05:51 UTC, lemunozm commented on src/interfaces/ERC6909/IERC6909MetadataExtension.sol
> +interface IERC6909MetadataExtension {
It does! Then I need to always use the `IERC6909Collateral` everywhere instead of `IERC6909` I guess.

I'm curious about where the name `Collateral` comes from. Why not just `Extension` (or `Ext`)? Not sure if collateral is the word 🤔

2024-10-24 05:56 UTC, lemunozm commented on src/ERC6909/ERC6909Errors.sol
> +error ERC6909Collateral_SetDecimal_LessThanMinimalDecimal(uint8 minimal, uint8 actual);
I have some thoughts/questions regarding this.

- Why not the event belongs to the interface? If they do, we do not need a long prefix name because the interface already adds the namespace. i.e: `ERC6909Collateral.Mint`

- I would go with the simplest solution by now, which is using a simpler name and iterate from it. If we need extra namespace we can modify it later.

2024-10-24 05:57 UTC, lemunozm commented on src/ERC6909/ERC6909.sol
> +        balanceOf[sender][id] -= amount;
Thanks for the explanation!

2024-10-24 06:39 UTC, lemunozm reviewed
Another review iteration. I think we need to solve the topic of multiple metadata per token, because it changes a lot of things from the implementation.

I missed some comments in some unchecked sections. Would love to have them 🙏🏻

2024-10-24 06:39 UTC, lemunozm commented on src/ERC6909/ERC6909.sol
> +                    require(newAllowance <= allowed, ERC6909_TransferFrom_InsufficientAllowance(msg.sender, tokenId));
The required line checks the above underflow condition after it can be underflowed. I think it will end up working fine, but it broke my mind, realizing it would not generate an error 😆. 

Could we check as `require(amount <= allowed, ...)` instead?

2024-10-24 06:39 UTC, lemunozm commented on src/ERC6909/ERC6909.sol
> +        }
You're assuming here all implementors of `ERC6909` will be `ERC6909Collateral`, but what if I create another inherited implementation? I could break such an invariant.

2024-10-24 06:39 UTC, lemunozm commented on src/interfaces/ERC6909/IERC6909Collateral.sol
> +    function mint(address _owner, string memory _tokenURI, uint256 _amount) external returns (uint256 _tokenId);
Why does mint receive the `tokenUri` as a param instead of the `tokenId` directly?

2024-10-24 06:39 UTC, lemunozm commented on src/ERC6909/ERC6909Collateral.sol
> +            require(totalSupply_ + _amount >= totalSupply_, OverflowUint256(totalSupply_, _amount));
Topic 2: `total_supply + amount` can lead to an overflow

2024-10-24 08:38 UTC, peculiarity commented on src/ERC6909/ERC6909Collateral.sol
> +            require(totalSupply_ + _amount >= totalSupply_, OverflowUint256(totalSupply_, _amount));
Here is the thing. There is no upper boundary for the totalSupply, except the `type(uint256).max` value.
What I'm checking here is actually if we are allowed to mint new tokens beyond the possible uint256 value.

2024-10-24 08:49 UTC, peculiarity commented on src/ERC6909/ERC6909.sol
> +        }
You are right!
Now that makes me think if we would like to have an internal `_mint` function that can be used in the implementation's `mint` function.

I get this feeling that I over engineered a little bit all the interfaces and contracts. I looked at how uniswap did it and some other libraries for ERC1155 ( OpenZeppelin )  but our case differs. We are the "users" of the `ERC6909` and we don't want to give some minimal generic functionality and let others do the full implementation. Probably we can have only `ERC6909` and that's it.

WDYT?

2024-10-24 08:50 UTC, peculiarity commented on src/ERC6909/ERC6909Collateral.sol
> +    /// @inheritdoc IERC6909Collateral
I can remove all of these and get back at them at a later iteration. if needed at all

2024-10-24 08:54 UTC, peculiarity commented on src/ERC6909/ERC6909Collateral.sol
> +            require(totalSupply_ + _amount >= totalSupply_, OverflowUint256(totalSupply_, _amount));
> Topic 2: `total_supply + amount` can lead to an overflow

That's the idea.If it overflows the amount will be less than the first number. `a+b=c ; c > a`. This is the check for overflowing. :)

2024-10-24 09:09 UTC, peculiarity commented on src/ERC6909/ERC6909Collateral.sol
> +            require(totalSupply_ + _amount >= totalSupply_, OverflowUint256(totalSupply_, _amount));
I changed my mind. Put some more thought about it and changed the error name

2024-10-24 09:10 UTC, peculiarity commented on src/ERC6909/ERC6909Collateral.sol
> +    /// @inheritdoc IERC6909Collateral
I removed them for now.

2024-10-24 09:14 UTC, peculiarity commented on src/ERC6909/ERC6909.sol
> +        }
For now I removed the `unchecked` mark and rely on it to overflow with the generic error.

2024-10-24 09:16 UTC, peculiarity commented on src/interfaces/ERC6909/IERC6909Collateral.sol
> +    function mint(address _owner, string memory _tokenURI, uint256 _amount) external returns (uint256 _tokenId);
Read the doc :D 
> TokenId is auto incremented by one.
    
 When you mint initially you don't know what the ID is but at the same time you want to provide the URI to the metadata.

2024-10-24 10:25 UTC, hieronx commented on src/ERC6909/ERC6909Collateral.sol
> +    /// @inheritdoc IERC6909Collateral
Yes having fungible collateral (quantity > 1) is an early idea that we need to explore more before we make a decision, so agreed that simplifying and keeping this out for now makes sense.

2024-10-24 10:27 UTC, hieronx commented on src/ERC6909/ERC6909Collateral.sol
> +        emit Transfer(msg.sender, address(0), _owner, _tokenId, _amount);
It is also in the spec: https://eips.ethereum.org/EIPS/eip-6909#events

> Transfer 
> MUST be logged with the sender address as the zero address when an amount of a token id is minted.

2024-10-24 10:30 UTC, ilinzweilin commented on src/ERC6909/ERC6909Collateral.sol
let's maybe change the name to ERC6909Centrifuge maybe? 
Collateral is very confusing as it is only one of the use cases for the nfts

2024-10-24 12:51 UTC, peculiarity commented on src/ERC6909/ERC6909Collateral.sol
Done

2024-10-24 17:50 UTC, lemunozm commented on src/ERC6909/ERC6909.sol
> +        }
I like what you posted about having just `ERC6909`. If we need more fine grain in the future, we can refactorize it. But for now, let's go simpler!

2024-10-24 17:51 UTC, lemunozm commented on src/interfaces/ERC6909/IERC6909Collateral.sol
> +    function mint(address _owner, string memory _tokenURI, uint256 _amount) external returns (uint256 _tokenId);
Mmm... I thought mint worked differently, I will check more deeply

2024-10-24 18:06 UTC, lemunozm commented on src/ERC6909/ERC6909Collateral.sol
> +            require(totalSupply_ + _amount >= totalSupply_, OverflowUint256(totalSupply_, _amount));
I think there could still be an error because the required check is also equals to. If
`_amount = uint256.max` It passes the condition. I think the check should be performed in the addition stage.

2024-10-25 12:38 UTC, lemunozm commented on src/interfaces/ERC6909/IERC6909.sol
> +    event Transfer(address caller, address indexed from, address indexed to, uint256 indexed id, uint256 amount);
Do we really want/need the `caller` here?

2024-10-25 12:38 UTC, lemunozm commented on src/ERC6909/ERC6909.sol
> +    function _transfer(address sender, address receiver, uint256 id, uint256 amount) private returns (bool) {
Curious about what's the "thought" regarding allowing a successful transfer when `sender` and `receiver` are the same account

2024-10-25 14:32 UTC, peculiarity commented on src/ERC6909/ERC6909Errors.sol
> +error ERC6909Collateral_SetDecimal_LessThanMinimalDecimal(uint8 minimal, uint8 actual);
I would love to hear the others as well.

2024-10-25 14:33 UTC, peculiarity commented on src/Deterministic.sol
> +    function _previewAddress(address deployer, bytes32 salt, bytes memory bytecode)
Been thinking today -  what about `generateAddress` ?

2024-10-25 14:37 UTC, peculiarity commented on src/ERC6909/ERC6909Collateral.sol
> +        emit Transfer(msg.sender, address(0), _owner, _tokenId, _amount);
> It is also in the spec: https://eips.ethereum.org/EIPS/eip-6909#events
> 
> > Transfer
> > MUST be logged with the sender address as the zero address when an amount of a token id is minted.

That doesn't force you to use `Transfer` per se. It just tells you that you must use the `zero` address for mints if you decide to go this way.

This is the real definition ( under definition section ) : 
> mint: The creation of an amount of tokens. This MAY happen in a mint method or as a transfer from the zero address.

Let's just agree if this is the way we would like to have it or just create a new Mint event.  I gave justification for my decision

2024-10-25 14:39 UTC, peculiarity commented on src/ERC6909/ERC6909Collateral.sol
> +            require(totalSupply_ + _amount >= totalSupply_, OverflowUint256(totalSupply_, _amount));
It doesn't  pass it . If the initial value is  `1` and you add `type(uint256).max` it will overflow to `0`. It cannot go to the same value.

2024-10-25 14:41 UTC, peculiarity commented on src/interfaces/ERC6909/IERC6909.sol
> +    event Transfer(address caller, address indexed from, address indexed to, uint256 indexed id, uint256 amount);
When you have any doubts , ask yourself .... not what Jesus would do  but rather what the standard says :sweat_smile:

2024-10-25 14:44 UTC, peculiarity commented on src/ERC6909/ERC6909.sol
> +    function _transfer(address sender, address receiver, uint256 id, uint256 amount) private returns (bool) {
I would assume that it's the same as if the `amount` is 0.
According to the ERC-20 spec:
>Note Transfers of 0 values MUST be treated as normal transfers and fire the Transfer event.

It isn't explicitly mentioned but my assumption that the behavior will be the same.

2024-10-25 14:59 UTC, lemunozm commented on src/Deterministic.sol
> +    function _previewAddress(address deployer, bytes32 salt, bytes memory bytecode)
"generate*" calls are usually not idempotent. Why do you not like the currently used name `getAddress`?

2024-10-25 15:00 UTC, lemunozm commented on src/ERC6909/ERC6909Collateral.sol
> +            require(totalSupply_ + _amount >= totalSupply_, OverflowUint256(totalSupply_, _amount));
Ah yes, you're right.

2024-10-25 15:01 UTC, lemunozm commented on src/interfaces/ERC6909/IERC6909.sol
> +    event Transfer(address caller, address indexed from, address indexed to, uint256 indexed id, uint256 amount);
xD. I didn't know that was mandatory by the standard 👍🏻

2024-10-25 15:16 UTC, lemunozm commented on src/ERC6909/ERC6909Centrifuge.sol
> +    uint8 public constant MIN_DECIMALS = 2;
NIT. Unused

2024-10-28 10:14 UTC, wischli reviewed
A few questions and nits from catching up with the latest changes. Feel free to ignore the nits.

2024-10-28 10:14 UTC, wischli commented on src/interfaces/ERC6909/IERC6909Centrifuge.sol
> +    /// @notice             Provide URI for a specific tokenId.
Ultra Nit: For some docs you use punctuation `.` but for others you don't. Would be great to be consistent

2024-10-28 10:14 UTC, wischli commented on src/interfaces/ERC6909/IERC6909Centrifuge.sol
> +    /// @param _owner       Creates suppy of a given _tokenId by _amount for _owner
Nit: Typo
```suggestion
    /// @param _owner       Creates supply of a given _tokenId by _amount for _owner
```

2024-10-28 10:14 UTC, wischli commented on src/ERC6909/ERC6909Centrifuge.sol
> +    function mint(address _owner, string memory _tokenURI, uint256 _amount) public auth returns (uint256 _tokenId) {
Nit question: Is it intended that this method can be called more than once for the same token URI or should there be an URI blacklist? I know the URI seems irrelevant except for the `TokenURI` event which can be emitted multiple times for the same `_URI` but different token ids.

2024-10-28 10:14 UTC, wischli commented on src/ERC6909/ERC6909Centrifuge.sol
> +        address _owner = msg.sender;
Nit: You are using both `_owner` as well as `msg.sender` in the scope of this function. Appears to me that this line can be removed OR only `_owner` be used.
```suggestion
```

2024-10-28 10:14 UTC, wischli commented on src/ERC6909/ERC6909.sol
> +        isOperator[msg.sender][operator] = approved;
Q: Above in `approve` ([L45](https://github.com/centrifuge/asset-pools/pull/12/files#diff-6ac1a1793b4b1e79786a190c8a3024a1bd74a4cdbbd0d1254698e1fe80abcc26R45)), we perform a read before a write. Here we don't. Is this intended? AFAIU, writing a `bool` should cost the same gas as writing a `uint256` but reading should be slightly lower for `bool` because it only retrieves one bit vs. the entire storage slot.

2024-10-28 10:14 UTC, wischli commented on src/interfaces/ERC6909/IERC6909Centrifuge.sol
> +    /// @param _owner       Creates suppy of a given _tokenId by _amount for _owner
```suggestion
    /// @param _owner       Creates supply of a given _tokenId by _amount for _owner
```

2024-10-28 10:14 UTC, wischli commented on src/interfaces/ERC6909/IERC6909Centrifuge.sol
> +    /// @param _amount      Amount by which the supply for _tokenId of _owner is increase by
Nit
```suggestion
    /// @param _amount      Amount by which the supply for _tokenId of _owner is increased by
```

2024-10-28 10:14 UTC, wischli commented on test/unit/ERC6909Centrifuge.t.sol
> +        assertEq(totalSupply, amount);
Nit: Shouldn't we also check that
```suggestion
        assertEq(totalSupply, amount);
        assertEq(balance, amount);
```

I know we are checking `mint` with zero amount below but that only implicitly checks the above.

2024-10-28 10:14 UTC, wischli commented on test/unit/ERC6909Centrifuge.t.sol
> +        assertTrue(isSuccessful);
Shouldn't this be false because we just set it to that?
```suggestion
        assertFalse(isSuccessful);
```

2024-10-28 10:14 UTC, wischli commented on test/unit/ERC6909Centrifuge.t.sol
> +        uint256 amount = 32;
Q: Curious why we don't fuzz this test?

2024-10-28 10:14 UTC, wischli commented on test/unit/ERC6909Centrifuge.t.sol
> +        // Caller is actually the owner
Nit: Move up comment

```suggestion
        // Caller is actually the owner
        vm.prank(delegate);
        isSuccessful = token.transferFrom(self, receiver, tokenId, sentAmount);

        remainingBalance = remainingBalance - sentAmount; // 8

        assertTrue(isSuccessful);
        assertEq(token.balanceOf(receiver, tokenId), receiverBalance + sentAmount);
        assertEq(token.balanceOf(self, tokenId), remainingBalance);
        assertEq(token.allowance(self, delegate, tokenId), allowance - sentAmount);

```

2024-10-28 10:14 UTC, wischli commented on test/unit/ERC6909Centrifuge.t.sol
> +        uint256 newAllowance = 1337;
Nit: `tokenId` could be `1337` as we don't assume inequality.

2024-10-28 10:14 UTC, wischli commented on test/unit/ERC6909Centrifuge.t.sol
> +        isSuccessful = token.approve(delegate, tokenId, amount);
Nit: Why are we not testing approval increments?

2024-10-28 10:14 UTC, wischli commented on test/unit/ERC6909Factory.t.sol
> +    function testDeterminism() public {
Nit: Shouldn't we fuzz the deployer address instead of hardcoding it to `0xdeadbeef`?

2024-10-28 15:22 UTC, peculiarity commented on test/unit/ERC6909Centrifuge.t.sol
> +        isSuccessful = token.approve(delegate, tokenId, amount);
What do you mean by approval increments in here ?

2024-10-28 15:24 UTC, peculiarity commented on test/unit/ERC6909Centrifuge.t.sol
> +        uint256 newAllowance = 1337;
It could be .. so what's your point ?

2024-10-28 15:27 UTC, peculiarity commented on test/unit/ERC6909Centrifuge.t.sol
> +        // Caller is actually the owner
That's is just wrong. 
When I call `token.mint` I call it from the test contract so the owner is actually the address of the `test` contract.
When I call `token.tranferFrom` at line 240 of the original call, this is a call triggered by the test contract itself ( `msg.sender` is the address of the test contract )

2024-10-28 15:33 UTC, peculiarity commented on test/unit/ERC6909Centrifuge.t.sol
> +        uint256 amount = 32;
We can discuss that in a meeting but the main reason or not using fuzzing here is:
I have higher control of the test data that is used. If I rely on some random number it will be harder for me to adjust for each scenario
As you can see I'm trying to test all possible paths in  a single test scenario and the reason behind this is  - This is how we did it in LP. I removes the constant duplicate of setup and it just  reads as a "story".
I think unit tests should be fast and more controller. We can provide fuzzin in integration tests which IMO should test everything in details.

2024-10-28 15:38 UTC, peculiarity commented on src/ERC6909/ERC6909Centrifuge.sol
> +        address _owner = msg.sender;
Good catch!

2024-10-28 15:42 UTC, peculiarity commented on test/unit/ERC6909Centrifuge.t.sol
> +        assertTrue(isSuccessful);
No, this checks if the transaction is successfully executed, not whether the value is true or false

2024-10-28 15:43 UTC, peculiarity commented on src/interfaces/ERC6909/IERC6909Centrifuge.sol
> +    /// @notice             Provide URI for a specific tokenId.
Would be indeed. Lol :)

2024-10-28 15:52 UTC, peculiarity commented on test/unit/ERC6909Centrifuge.t.sol
> +        assertEq(totalSupply, amount);
If you are referring whether I would like to test `assertEq(balance, amount)` then my answer to your question is: No, we don't have to check it out :)
So I wrote a specific scenario testing the function `mint` with the ` function mint(address _owner, string memory _tokenURI, uint256 _amount) `
So in here I used again the same function. There is no need to test that again and the reasoning is:
 -  If I call `mint` in 50 tests , does that mean I have to test that every time it is called, the balance is increased by `amount`?

2024-10-28 16:04 UTC, peculiarity commented on src/ERC6909/ERC6909Centrifuge.sol
> +    function mint(address _owner, string memory _tokenURI, uint256 _amount) public auth returns (uint256 _tokenId) {
so your concern is whether this method should be called with the same tokenURI twice?
If that's the case then I can elaborate more on how I think about it.

Let's say issuer  submits two tokens  with the same tokenURI ( probably they forgot  to change the URI ). They can always call `setTokenURI` and fix the thing.  I'm not sure if it's not possible to have 2 items with the same URI. I guess we can discuss that further. 

For me it's not a blocker or an issue. IF i have to track the token URI's , IMO that is additional storage variable, additional gas and additional complexity

2024-10-28 16:11 UTC, wischli commented on test/unit/ERC6909Centrifuge.t.sol
> +        isSuccessful = token.approve(delegate, tokenId, amount);
I was referring to increasing the amount and checking the allowance amount post calling `approve`. Same also for decreasing.

2024-10-28 16:13 UTC, wischli commented on test/unit/ERC6909Centrifuge.t.sol
> +        assertTrue(isSuccessful);
Ah thanks!

2024-10-28 16:14 UTC, wischli commented on test/unit/ERC6909Centrifuge.t.sol
> +        uint256 newAllowance = 1337;
Sorry, invalid point from my side

2024-10-28 16:15 UTC, peculiarity commented on src/ERC6909/ERC6909.sol
> +        isOperator[msg.sender][operator] = approved;
I see your point. 
Yeah I think it's better to check whether the status is different and then set it .
Reading won't differ.  Even thought bool is a single bit you always work on word level so it will be stored as a whole 32bytes slot. So that 1 bit will be padded and stored. When you read, you read the whole slot anyways .

2024-10-28 16:16 UTC, peculiarity commented on src/ERC6909/ERC6909.sol
> +        isOperator[msg.sender][operator] = approved;
In this case it is not applicable but in general if you have a boolean value as a storage variable, there is actually  a gas optimization trick to use `uint256` with `1` and `2` as values. Read more about it [here](https://detectors.auditbase.com/int-instead-of-bool-gas-optimization)

2024-10-28 16:16 UTC, wischli commented on test/unit/ERC6909Centrifuge.t.sol
> +        uint256 amount = 32;
Interesting perspective! I am of the opposite opinion but definitely don't have a strong opinion. Happy to discuss this over a beer at the offsite. Curious about everyones thoughts!

2024-10-28 16:24 UTC, wischli commented on test/unit/ERC6909Centrifuge.t.sol
> +        assertEq(totalSupply, amount);
My point is: Both variants of `mint` function set the `balanceOf` entry of `[_owner][_tokenId]`. However, we are only ensuring the correct `balanceOf` setting in the variant with the `_tokenId` as part of the signature, not the one with the `_tokenURI` as input argument.

2024-10-28 16:40 UTC, peculiarity commented on test/unit/ERC6909Centrifuge.t.sol
> +        isSuccessful = token.approve(delegate, tokenId, amount);
Just increasing and decreasing value and using these value with `approve` doesn't differ from just updating with some value.  There is absolutely nothing you are testing with this.  

```
uint256 allowance = 100;

token.approve(someone, allowance)
assertEq(allowance, token.allowance(someone))

uint256 decreased = allowance - 10;
token.approve(someone, decreased);
assertEq(decreased, token.allowance(someone));

uint256 inreased = allowance + 30; // or decreased + 30
token.approve(someone, decreased);
assertEq(increased, token.allowance(someone));
```

In this pseudo code I think I refer to what you mean. So the `decreaed` and `increased` values are absolutely nothing special for the `approve` method. The idea is to test that when `approved` is called with `value != allowance` , the new allowance is updated. How this value is calculated has nothing to do with `approve` functionality.

2024-10-28 17:05 UTC, wischli commented on src/ERC6909/ERC6909Centrifuge.sol
> +    function mint(address _owner, string memory _tokenURI, uint256 _amount) public auth returns (uint256 _tokenId) {
Yes this was my concern, especially in regards to the _genesis_ token URI, for which a token was created. I can imagine frontends to rely on the `TokenURI` event such that they will update the token ID for the same token URI without knowing that both should co-exist.

2024-10-28 17:08 UTC, wischli commented on test/unit/ERC6909Centrifuge.t.sol
> +        // Caller is actually the owner
Ah thanks, I was missing that!

2024-10-28 17:08 UTC, wischli commented on test/unit/ERC6909Centrifuge.t.sol
> +        isSuccessful = token.approve(delegate, tokenId, amount);
Awesome thanks for elaborating! Case closed

2024-10-28 17:28 UTC, peculiarity commented on test/unit/ERC6909Centrifuge.t.sol
> +        uint256 amount = 32;
Yeah, I'm also not like super biased. If you see my other tests, you can see that I applied fuzzing but in here I wanted to have control of the amount variable.

2024-10-28 17:33 UTC, peculiarity commented on src/ERC6909/ERC6909Centrifuge.sol
> +    function mint(address _owner, string memory _tokenURI, uint256 _amount) public auth returns (uint256 _tokenId) {
I don't think it's an issue. Most likely this will be handled by subquery. So you create 2 tokenId with the same tokenUri but then for the second tokenId you fire a new TokenID event. This will be caught by the subquery processor and update the record in their offchain database. The front end just have to fetch that data on each page load and that's it :)  I don't see issues

2024-10-29 12:27 UTC, hieronx commented on src/Deterministic.sol
> +    function _previewAddress(address deployer, bytes32 salt, bytes memory bytecode)
@peculiarity why is this in an abstract contract rather than a library? It has no state, so seems like a library would work just fine.

2024-10-29 12:28 UTC, hieronx commented on src/ERC6909/ERC6909Errors.sol
> +error ERC6909Collateral_SetDecimal_LessThanMinimalDecimal(uint8 minimal, uint8 actual);
I think prefixes are not really required for errors, they are anyways namespaced by the contract name in any indexer/UI.

2024-10-29 12:28 UTC, hieronx commented on src/ERC6909/ERC6909Errors.sol
> +error ERC6909Collateral_SetDecimal_LessThanMinimalDecimal(uint8 minimal, uint8 actual);
Why are errors in this file rather than in the interface?

2024-10-29 12:29 UTC, hieronx commented on src/ERC6909/ERC6909Errors.sol
> +error ERC6909Collateral_SetDecimal_LessThanMinimalDecimal(uint8 minimal, uint8 actual);
I think we should follow Uniswap and put custom errors in interfaces.

2024-10-29 12:31 UTC, hieronx commented on src/ERC6909/ERC6909Collateral.sol
> +        emit Transfer(msg.sender, address(0), _owner, _tokenId, _amount);
We should go with Transfer, the spec does make this clear, and every implementation of ERC20 does the same.

2024-10-29 12:33 UTC, hieronx commented on src/ERC6909/ERC6909Centrifuge.sol
> +    function mint(address _owner, string memory _tokenURI, uint256 _amount) public auth returns (uint256 _tokenId) {
I think multiple items with the same token ID is fine. If you have a metadata file like
```json
{ 
  "name": "Cash account"
}
```

and 2 users both independently pin this on IPFS, they will end up with the same IPFS hash since it's determinstic based on the file contents. Thus they will have 2 different NFTs/items with the same token uri.

2024-10-29 14:09 UTC, lemunozm commented on src/Deterministic.sol
> +    function _previewAddress(address deployer, bytes32 salt, bytes memory bytecode)
I think it's already changed

2024-10-29 14:23 UTC, peculiarity commented on src/ERC6909/ERC6909Collateral.sol
> +        emit Transfer(msg.sender, address(0), _owner, _tokenId, _amount);
It is `Transfer` so we are good to go. I mark this as resolved.

2024-10-29 14:28 UTC, peculiarity commented on src/ERC6909/ERC6909Errors.sol
> +error ERC6909Collateral_SetDecimal_LessThanMinimalDecimal(uint8 minimal, uint8 actual);
Since this is the first time we work with custom errors  I didn't know how to approach this. As I mentioned earlier, I took the inspiration from [here](https://github.com/PaulRBerg/prb-math/blob/main/src/sd1x18/Errors.sol)

I can move them into the interface.

2024-10-29 15:13 UTC, lemunozm commented on src/ERC6909/ERC6909Errors.sol
> +error ERC6909Collateral_SetDecimal_LessThanMinimalDecimal(uint8 minimal, uint8 actual);
I would say, let's move errors to interface by now. In the offsite, we can discuss this and follow another approach if needed

2024-10-30 09:36 UTC, peculiarity commented on src/Deterministic.sol
> +    function _previewAddress(address deployer, bytes32 salt, bytes memory bytecode)
It is changed indeed.

2024-10-30 09:36 UTC, peculiarity commented on src/ERC6909/ERC6909Errors.sol
> +error ERC6909Collateral_SetDecimal_LessThanMinimalDecimal(uint8 minimal, uint8 actual);
Done

2024-10-30 10:03 UTC, lemunozm commented on src/ERC6909/ERC6909Errors.sol
> +error ERC6909Collateral_SetDecimal_LessThanMinimalDecimal(uint8 minimal, uint8 actual);
Thanks!

I think prb-math uses this pattern because:
- They do not have such an interface to deal with.
- The errors from them are very very generic and mathematical related.

Instead, for our use case, we have a strict interface to follow and the errors depend on that specification

2024-10-30 11:29 UTC, hieronx approved these changes
I left a bunch of mostly nitpick comments, so please feel free to merge without addressing any of them now. Overall this is looking really really solid already, great work!

2024-10-30 11:29 UTC, hieronx commented on src/ERC6909/ERC6909.sol
> +    function transfer(address receiver, uint256 id, uint256 amount) external virtual returns (bool) {
Super nit: sometimes it is `tokenId` (e.g. in `transferFrom`), sometimes it is `id`. I would consistently use one or the other.

2024-10-30 11:29 UTC, hieronx commented on src/ERC6909/ERC6909.sol
> +        if (isOperator[msg.sender][operator] != approved) {
I think here + in `approve`, the if statement should be removed at least for the event. See https://github.com/Uniswap/v4-core/blob/main/src/ERC6909.sol#L61 and other ERC20 implementations, where the event is always emitted, even if there was no change.

2024-10-30 11:29 UTC, hieronx commented on src/ERC6909/ERC6909.sol
> +    mapping(address owner => mapping(address spender => mapping(uint256 id => uint256 amount))) public allowance;
Small style suggestion, I think the names of the values are not needed since they are redundant with the actual storage variable names:
```suggestion
    mapping(address owner => mapping(uint256 id => uint256)) public balanceOf;
    mapping(address owner => mapping(address operator => bool)) public isOperator;
    mapping(address owner => mapping(address spender => mapping(uint256 id => uint256))) public allowance;
```

2024-10-30 11:29 UTC, hieronx commented on src/ERC6909/ERC6909Centrifuge.sol
> +    function setTokenURI(uint256 _tokenId, string memory _URI) public auth {
We use underscore prefixes for internal variables/functions, and underscore postfixes to avoid variable shadowing. So here it should be postfixes (as in the other function parameters).

2024-10-30 11:29 UTC, hieronx commented on src/ERC6909/ERC6909Centrifuge.sol
> +        emit TokenURI(_tokenId, _URI);
Maybe:
```suggestion
        emit SetTokenURI(_tokenId, _URI);
```

2024-10-30 11:29 UTC, hieronx commented on src/ERC6909/ERC6909Centrifuge.sol
> +    /// @inheritdoc IERC6909Centrifuge
I think it would make more sense to move `setTokenURI` below `mint` and `burn`.

2024-10-30 11:29 UTC, hieronx commented on src/ERC6909/ERC6909Centrifuge.sol
> +        setTokenURI(_tokenId, _tokenURI);
Super nit: I think empty lines help create logical organization of code that belongs together, and here it can be grouped like:
```suggestion
        _tokenId = ++latestTokenId;

        balanceOf[_owner][_tokenId] = _amount;
        totalSupply[_tokenId] = _amount;
        setTokenURI(_tokenId, _tokenURI);
```

2024-10-30 11:29 UTC, hieronx commented on src/ERC6909/ERC6909Centrifuge.sol
> +        /// @dev    The require check above guarantees that you cannot burn more than you have.
nit: for inline comments you don't really need natspec annotations
```suggestion
        // The require check above guarantees that you cannot burn more than you have.
```

2024-10-30 11:29 UTC, hieronx commented on src/ERC6909/ERC6909Centrifuge.sol
> +        emit ContractURI(address(this), _URI);
Maybe:
```suggestion
        emit SetContractURI(address(this), _URI);
```

2024-10-30 11:29 UTC, hieronx commented on src/ERC6909/ERC6909Factory.sol
> +    function deploy(address owner, bytes32 salt) public auth returns (address collateral) {
I think this can be permissionless, no `auth` needed

2024-10-30 11:29 UTC, hieronx commented on src/libraries/StringLib.sol
> +    function toString(uint256 value) internal pure returns (string memory) {
I think this is unused now, right?

2024-10-30 11:31 UTC, hieronx commented on src/utils/Deployment.sol
> +function previewAddress(address deployer, bytes32 salt, bytes memory bytecode) pure returns (address instance) {
I wonder what is the tradeoff of a free function vs a library. It seems more logical to me to move this to a `FactoryLib`, but I don't have a strong argument in favour of this besides code organization.

2024-10-30 12:02 UTC, lemunozm commented on src/utils/Deployment.sol
> +function previewAddress(address deployer, bytes32 salt, bytes memory bytecode) pure returns (address instance) {
I was all the time reading "previous" here when it is "preview" 😆. Sorry for the old thread regarding this. I think `preview` makes sense 👍🏻

2024-10-30 14:37 UTC, peculiarity commented on src/utils/Deployment.sol
> +function previewAddress(address deployer, bytes32 salt, bytes memory bytecode) pure returns (address instance) {
@hieronx  Let's try to add the question the other way around - Why create a library? 
> Free functions are always internal functions and are meant to replace internal library functions and their very special behaviour.

I guess if there are multiple reusable functions that work on the same type, might be a good idea to combine them into a library. Also free functions can accept ETH for example or change contracts storage variables.

I don't see a single reason why go with library.

2024-10-30 15:05 UTC, peculiarity commented on src/ERC6909/ERC6909Centrifuge.sol
> +    function setTokenURI(uint256 _tokenId, string memory _URI) public auth {
That's true. My bad  :)

2024-10-30 15:09 UTC, hieronx commented on src/utils/Deployment.sol
> +function previewAddress(address deployer, bytes32 salt, bytes memory bytecode) pure returns (address instance) {
That's why I said "I wonder what is the tradeoff of a free function vs a library". It is an open question to me, that I think we should look into more. 

I do think splitting up utilities across libraries and non libraries is more confusing than just putting all of them in libraries, and that itself is a (not very strong, but still somewhat) argument to use a library here.

2024-10-30 15:40 UTC, lemunozm commented on src/utils/Deployment.sol
> +function previewAddress(address deployer, bytes32 salt, bytes memory bytecode) pure returns (address instance) {
Giving my unsolicited (and probably non-expert & nooby) opinion 😄:

I feel like libraries just add a namespace and the possibility of using the functions as methods for the first argument. It gives some meaning of "object" without really have an object, or a "set" of methods belonging to something.

I would not go with a library if those offered features don't mean anything for the behavior of the function. I think this is the case here.

2024-10-30 22:53 UTC, peculiarity commented on src/ERC6909/ERC6909Centrifuge.sol
> +        emit TokenURI(_tokenId, _URI);
I'd rather go with `TokenURISet` and `ContractURISet`. The reason for that is because for example when you call 
`setOperator` you emit `OperatorSet` so I would go with the same pattern.

2024-10-30 22:54 UTC, peculiarity commented on src/ERC6909/ERC6909Centrifuge.sol
> +        setTokenURI(_tokenId, _tokenURI);
I understand that the empty lines are used to differentiate the different logical parts and that's why almost everything is on a separate line. What's the common logical bit there? If it is an assignment of a value, then probably there should be an empty line between `_tokenId= ++latestTokenId` and the line beloow.

2024-10-30 23:00 UTC, peculiarity commented on src/utils/Deployment.sol
> +function previewAddress(address deployer, bytes32 salt, bytes memory bytecode) pure returns (address instance) {
For now I will leave it as it is . We can always put it into a library.

2024-10-31 07:11 UTC, hieronx commented on src/ERC6909/ERC6909Centrifuge.sol
> +        emit TokenURI(_tokenId, _URI);
Makes sense to me! 👍

2024-10-31 12:35 UTC, hieronx commented on src/ERC6909/ERC6909.sol
> +abstract contract ERC6909 is IERC6909, IERC165 {
I would inherit `IERC6909` from `IERC165` in the interface file

2024-10-31 12:35 UTC, hieronx commented on src/ERC6909/ERC6909Factory.sol
> +        collateral = address(new ERC6909NFT{salt: salt}(owner));
Would be nice to emit an event here, `NewDeployment` or something like that. We didn't do this in liquidity pools because there were equivalent events in pool mgr that called the factories.

2024-10-31 12:35 UTC, hieronx commented on src/libraries/StringLib.sol
> +        return keccak256(abi.encodePacked(value)) == EMPTY_STRING;
I bet
```suggestion
        return bytes(value).length == 0;
```
will be much cheaper

2024-10-31 12:50 UTC, lemunozm approved these changes
Agree with the latest Jeroen comments, but appart from that LGTM. Let's merge this today!

2024-10-31 13:02 UTC, peculiarity commented on src/ERC6909/ERC6909.sol
> +abstract contract ERC6909 is IERC6909, IERC165 {
Any pros/cons that you can think of ? 
Here is my thinking.

If out contracts needs a highly customized set of functions from various interfaces ( IERC6909, IERC165 ) , implementing multiple interfaces directly is often the better choice. 

If we have multiple contracts with the same combined functionality (i.e., implementing the same set of interfaces), creating an extended interface and implementing that can make the code cleaner and more maintainable.

But here is the thing, whatever ERC6909 implementation we have, they will inherit from ERC6909 abstract contract. 

 I'd guess your reasoning is that ERC6909 MUST be ERC165 compliant hence ERC165 is actually part of ERC6909. 
 
 So share your thoughts with me :)

2024-10-31 13:06 UTC, hieronx commented on src/ERC6909/ERC6909.sol
> +abstract contract ERC6909 is IERC6909, IERC165 {
> I'd guess your reasoning is that ERC6909 MUST be ERC165 compliant hence ERC165 is actually part of ERC6909.

Exactly this ☝️ 

Similar to how IERC7540 inherits from IERC165.

Even I consider this a pretty minor point though, also fine to leave it as is.

2024-10-31 13:10 UTC, peculiarity commented on src/libraries/StringLib.sol
> +        return keccak256(abi.encodePacked(value)) == EMPTY_STRING;
Ok... that's a good one!

2024-10-31 13:43 UTC, hieronx commented on src/libraries/StringLib.sol
> +        return bytes(value).length == 0;
At this point I'd argue this could just be inline within the contract, doesn't really need a library. But fine to keep as is!

2024-10-31 13:43 UTC, hieronx approved these changes

2024-10-31 14:06 UTC, peculiarity commented on src/libraries/StringLib.sol
> +        return bytes(value).length == 0;
Thought about it but then I realized that we used it.
Next person that will need some check ( if need it at  all ) might wonder how to do it .
I think it is better to have it. It doesn't have that much penalty on the code.

2024-10-31 15:50 UTC, lemunozm approved these changes

2024-11-06 08:19 UTC, merged

2024-11-11 09:04 UTC, lemunozm commented on src/ERC6909/ERC6909.sol
> +        require(amount > 0, EmptyAmount());
@peculiarity, it seems like these two lines do not have coverage. Could you add a super simple PR with just two use cases for them?