Holdings contract implementation
centrifuge/protocol-v3 pull request #42
Opened 2024-12-12 10:19 UTC by lemunozm

## Architecture

The first implementation of an `IItemManager` where `ItemId` represents` (ShareClassId, AssetId)`

2024-12-12 13:52 UTC, mustermeiszer commented
@lemunozm can you explain in more detail what the overall flow will be with the additional managers and? What will `AccountingItemManager` do?

2024-12-12 15:46 UTC, lemunozm commented
`AccountingItemManager` contract is just a superclass of `Holdings`, so it is the "same" contract (at least by now) than `Holdings`. I split just because that logic will be shared among all `ItemManager`. 

I think everything will be more understandable when I finish with the `PoolManager`

2024-12-12 16:04 UTC, wischli reviewed
Thanks for starting with this already!

2024-12-12 16:04 UTC, wischli commented on src/interfaces/IAccountingItemManager.sol
> +    function setItemAccounts(PoolId poolId, ItemId itemId, Accounts calldata itemAccounts) external;
Is it guaranteed that each ItemManager has at most one `Accounts` or could they have multiple?

2024-12-12 16:04 UTC, wischli commented on src/Holdings.sol
> +    function increase(PoolId poolId, ItemId itemId, uint128 amount) external auth returns (uint128 deltaValue) {
Nit: You can name this `amountValue` to not have to initialize that later and potentially skip the `return ...` line.
```suggestion
    function increase(PoolId poolId, ItemId itemId, uint128 amount) external auth returns (uint128) {
```

2024-12-12 16:10 UTC, lemunozm commented on src/interfaces/IAccountingItemManager.sol
> +    function setItemAccounts(PoolId poolId, ItemId itemId, Accounts calldata itemAccounts) external;
AFAIK, each item can have one `Accounts`, but one `Accounts` implies 4 `AccountId`s: equity, asset, loss, gain accounts

2024-12-12 16:11 UTC, lemunozm commented on src/interfaces/IAccountingItemManager.sol
> +    function setItemAccounts(PoolId poolId, ItemId itemId, Accounts calldata itemAccounts) external;
Each item of each `ItemManager` should be identical in this regard if I'm not mistaken. cc @mustermeiszer

2024-12-13 10:28 UTC, mustermeiszer commented on src/interfaces/IAccountingItemManager.sol
> +    function setItemAccounts(PoolId poolId, ItemId itemId, Accounts calldata itemAccounts) external;
No, you can not generalize that for all `ItemManagers`. That was just the first draft for `Tokens`. It should be sufficient for most use-cases though. 

But if I understand the interface correctly, all that it is doing here, is to allow to set an arbitrary amount of accounts, right?

2024-12-13 10:28 UTC, mustermeiszer commented on src/interfaces/IAccountingItemManager.sol
> +    function setItemAccounts(PoolId poolId, ItemId itemId, Accounts calldata itemAccounts) external;
What is `ItemId` in these cases?

2024-12-13 12:55 UTC, lemunozm commented on src/interfaces/IAccountingItemManager.sol
> +    function setItemAccounts(PoolId poolId, ItemId itemId, Accounts calldata itemAccounts) external;
I understood that all implementations of `IItemManager` should have (at least) those 4 accounts: equity, asset, loss, gain. For example, an item from `Bonds`, should also have those because you can track in the `Accounting` that information regarding those accounts. i.e. adding a loss for a bond item.

Is my assumption false?

> But if I understand the interface correctly, all that it is doing here, is to allow to set an arbitrary amount of accounts, right?

`Accounts` is:
```solidity
struct Accounts {
    AccountId asset;
    AccountId equity;
    AccountId loss;
    AccountId gain;
}
```

So you can specify those accounts per item.

> What is ItemId in these cases?

For `Tokens` (aka `Holdings`), an `ItemId` can be mapped to `(ShareClassId, AssetId)`. I think this is the correct output from the thread regarding this (see `PoolManager` impl to check the usage)

2024-12-17 09:15 UTC, lemunozm commented on src/Holdings.sol
> +    function increase(PoolId poolId, ItemId itemId, uint128 amount) external auth returns (uint128 deltaValue) {
Done, good recommendation!

2024-12-17 11:55 UTC, lemunozm commented
Ready to review (pending tests, events and possibly some errors). Let's focus by now in the logic itself

Happy to merge the AccountingElementManager with the Holdings implementation as long as I can have those 4 accounts in the IItemManager interface.

The usage of this accounts can be easier seen in the PoolManager PR: https://github.com/centrifuge/pools-internal/pull/36

2024-12-18 20:00 UTC, mustermeiszer reviewed
Looks great already! Really astonighing how quickly you and William picked up speed!

2024-12-18 20:00 UTC, mustermeiszer commented on src/AccountingItemManager.sol
> +contract AccountingItemManager is Auth, IAccountingItemManager {
abstract

2024-12-18 20:00 UTC, mustermeiszer commented on src/Holdings.sol
> +        delete items[poolId][itemId];
I think we should never allow that. Reusing ids seems always like a bad idea.

2024-12-18 20:00 UTC, mustermeiszer commented on src/Holdings.sol
> +    function increase(PoolId poolId, ItemId itemId, uint128 amount) external auth returns (uint128 amountValue) {
```suggestion
    function increase(PoolId poolId, ItemId itemId, uint128 amount, uint128 valuation) external auth returns (uint128 amountValue) {
```

We need to support increasing and decreasing with a value in order to note valuations correctly.

2024-12-18 20:00 UTC, mustermeiszer commented on src/Holdings.sol
> +        amountValue = uint128(item.valuation.getQuote(amount, AssetId.unwrap(item.assetId), poolCurrency));
Remove valuation here and use from input.

2024-12-18 20:00 UTC, mustermeiszer commented on src/Holdings.sol
> +    }
Can we also have it the other way around?

2024-12-18 20:00 UTC, mustermeiszer commented on src/Holdings.sol
> +    }
we are missing the counterpart here, right? `increaseInterest`

2024-12-18 20:00 UTC, mustermeiszer commented on src/Holdings.sol
> +        // TODO: should we initialize the accounts from AccountingItemManager here?
We have accounts per `item` not for all holdings of a pool or share class

2024-12-18 20:00 UTC, mustermeiszer commented on src/interfaces/IAccountingItemManager.sol
> +    function setItemAccounts(PoolId poolId, ItemId itemId, Accounts calldata itemAccounts) external;
So the UI would need to do that during creation after calling `create`, right?

2024-12-18 20:00 UTC, mustermeiszer commented on src/interfaces/IItemManager.sol
> +    function decreaseInterest(PoolId poolId, ItemId itemId, uint128 amount) external;
missing counterpart.

2024-12-18 20:00 UTC, mustermeiszer commented on src/interfaces/IItemManager.sol
> +}
Doc off. 

rather does update the stored `valuation` of an item using the valuation method

2024-12-18 20:00 UTC, mustermeiszer commented on src/interfaces/IItemManager.sol
> +interface IItemManager is IAccountingItemManager {
Can we also have methods that allow updating the valuation method of an item? Not sure, maybe to flexible...

2024-12-18 20:00 UTC, mustermeiszer commented on src/interfaces/IItemManager.sol
> +interface IItemManager is IAccountingItemManager {
I bet we will need that ^^

2024-12-19 07:14 UTC, lemunozm commented on src/Holdings.sol
> +    function increase(PoolId poolId, ItemId itemId, uint128 amount) external auth returns (uint128 amountValue) {
Do you want to mean something like a "settlementPrice" that should be optional, right?

2024-12-19 07:17 UTC, lemunozm commented on src/Holdings.sol
> +    function increase(PoolId poolId, ItemId itemId, uint128 amount) external auth returns (uint128 amountValue) {
Could a workaround be:

```solidity
prev = getValuation()
updateValuation(customFixedValuation)
increase()
updateValuation(prev)
```

2024-12-19 07:18 UTC, lemunozm commented on src/Holdings.sol
> +    }
For sure, just by now I didn't need it in the code base

2024-12-19 07:19 UTC, lemunozm commented on src/Holdings.sol
> +    }
I understood the interest always increased internally for some IItemManager implementations. Do we also have a way to set that interest directly?

2024-12-19 07:22 UTC, lemunozm commented on src/interfaces/IItemManager.sol
> +interface IItemManager is IAccountingItemManager {
Yeah, it is `updateValuation()`, but as you correctly pointed out, the doc was wrong.

2024-12-19 07:22 UTC, lemunozm commented on src/Holdings.sol
> +        delete items[poolId][itemId];
> Reusing ids

That's at least not the intention. Where is the ID reused? Here, we just remove the item from the storage (I would also need to remove it from `itemsIds` storage, BTW). But we never reuse an id, that's for sure

2024-12-19 07:25 UTC, lemunozm commented on src/Holdings.sol
> +        // TODO: should we initialize the accounts from AccountingItemManager here?
I'm not sure if I understand what you mean here.

The accounts are per `ItemId`, which means the accounts are also per `PoolId => ShareClassId => AssetId`. Is that not correct?

2024-12-19 07:27 UTC, lemunozm commented on src/Holdings.sol
> +        amountValue = uint128(item.valuation.getQuote(amount, AssetId.unwrap(item.assetId), poolCurrency));
I do not understand this. I thought the valuation used should be the one attached to the item. Could you explain a bit more about the whys?

2024-12-19 08:10 UTC, mustermeiszer commented on src/Holdings.sol
> +    }
We should defintely allow to set it manually in case there are errors.

2024-12-19 08:10 UTC, mustermeiszer commented on src/Holdings.sol
> +    function increase(PoolId poolId, ItemId itemId, uint128 amount) external auth returns (uint128 amountValue) {
But that enforces to always have a second contract that actually impelemnts `IERC7726 `. I think that is not really feasible. IMO, `increase`/`decrease` are flexible with given "`settlementPrice`" parameter. `update` actual uses the set valuation method.

2024-12-19 08:10 UTC, mustermeiszer commented on src/interfaces/IItemManager.sol
> +interface IItemManager is IAccountingItemManager {
Haha. Sorry, I already forgot that when I arrived at that point here. Perfect!

2024-12-19 08:28 UTC, lemunozm commented on src/Holdings.sol
> +    function increase(PoolId poolId, ItemId itemId, uint128 amount) external auth returns (uint128 amountValue) {
Ok, now I understand you.

I already had some thoughts about this. My idea is to offer a IERC7726 implementation that the FM can access (not the feeders), which just sets the values to what they want.

The above should be:

```solidity
prev = getValuation()
settlementPriceOracle.set(assetId, value)
updateValuation(settlementPriceOracle)
increase()
updateValuation(prev)
```

My intention with this is to let the `IItemManager.increase()` interface as simply as possible because different implementations should behave differently. i.e. The bonds could not use a custom settlement price and could use the valuation computed on-chain. That should happen each time we want to compute the NAV for them, so we should be able to not give a list of automated prices each time.

My point is, let this valuation be as much automated as possible unless you want to force some value manually

2024-12-19 09:03 UTC, lemunozm commented on src/interfaces/IAccountingItemManager.sol
> +    function setItemAccounts(PoolId poolId, ItemId itemId, Accounts calldata itemAccounts) external;
Yes, or in the same `create()`, we can add a new parameter to set the accounts. Does it make more sense?

2024-12-19 09:16 UTC, lemunozm commented on src/Holdings.sol
> +    }
Ok, thinking out loud and making a note for myself:

In bonds, if we compute the debt with `LinearAccrual`, and the FM calls `increaseInterest()`, I think internally we should modify the `normalizedDebt` to achieve a debt proportional to the increased interest. Maybe we need some method to perform this computation in `LinearAccrual` contract or in the associated library.

2024-12-19 09:30 UTC, lemunozm commented on src/Holdings.sol
> +        amountValue = uint128(item.valuation.getQuote(amount, AssetId.unwrap(item.assetId), poolCurrency));
Discussion in the above thread

2024-12-19 10:26 UTC, wischli reviewed
Great work so far! Looking forward to the tests. A few questions and nits from my side.

2024-12-19 10:26 UTC, wischli commented on src/Holdings.sol
> +        // TODO: should we initialize the accounts from AccountingItemManager here?
>  TODO: should we initialize the accounts from AccountingItemManager here?

I am curious how you would initialize the accounts in the constructor then which doesn't know about any `poolId` etc?

2024-12-19 10:26 UTC, wischli commented on src/Holdings.sol
> +        itemIds[poolId][item.scId][item.assetId] = ItemId.wrap(0);
Nit: Couldn't we just delete this entry as well instead of setting it to 0? Probably more or less same gas. Just think it looks cleaner.

2024-12-19 10:26 UTC, wischli commented on src/interfaces/IItemManager.sol
> +    /// @return value The value the item has increment.
Nit: I suppose `value` is the updated value and not only the incremented part?

```suggestion
    /// @return value The value of the item after incrementing.
```

2024-12-19 10:26 UTC, wischli commented on src/interfaces/IItemManager.sol
> +    /// @return value The value the item has decrement.
Nit: I suppose `value` is the updated value and not only the incremented part?

```suggestion
Nit: I suppose value is the updated value and not only the incremented part?

Suggested change
    /// @return value The value of the item after decrementing.
```

2024-12-19 10:26 UTC, wischli commented on src/interfaces/IItemManager.sol
> +    /// @notice Decrements the amount of an item as interest.
Nit: This comment throws me of. IIUC, it decreases the interest of the item and implicitly its value due to renormalizing based on the decreased interest?

2024-12-19 10:48 UTC, lemunozm commented on src/Holdings.sol
> +        // TODO: should we initialize the accounts from AccountingItemManager here?
Ouch! sorry I've just realized I wrote that comment in the wrong method! I wanted to write it down in the `create()` method. The accounts should be another parameter of `create()`

2024-12-19 10:49 UTC, lemunozm commented on src/Holdings.sol
> +        itemIds[poolId][item.scId][item.assetId] = ItemId.wrap(0);
I tried that before, but solidity does let me. Or I'm missing something, or I can only delete stuff when it's an struct

2024-12-19 10:51 UTC, lemunozm commented on src/Holdings.sol
> +        itemIds[poolId][item.scId][item.assetId] = ItemId.wrap(0);
Or at least not with a type wrapper as `ItemId`:

```
Error:
Compiler run failed:
Error (9767): Built-in unary operator delete cannot be applied to type ItemId.
  --> src/Holdings.sol:52:9:
   |
52 |         delete itemId[poolId][item_.scId][item_.assetId];
```

2024-12-19 10:51 UTC, lemunozm commented on src/Holdings.sol
> +        itemIds[poolId][item.scId][item.assetId] = ItemId.wrap(0);
Seems you can not with user defined types: https://ethereum.stackexchange.com/questions/112266/how-do-i-delete-entries-from-mappings-with-user-defined-types

2024-12-19 10:53 UTC, lemunozm commented on src/interfaces/IItemManager.sol
> +    /// @return value The value the item has increment.
As I envisioned this, it should be the incremented part, because that would be the amount used later in `updateEntry()`

2024-12-19 10:54 UTC, lemunozm commented on src/interfaces/IItemManager.sol
> +    /// @return value The value the item has increment.
The value of the item can be retrieved calling `itemValue()` after `increase()`, but the only way to know what was de difference of that increment is returning it in that moment

2024-12-19 11:09 UTC, lemunozm commented on src/interfaces/IItemManager.sol
> +    /// @notice Decrements the amount of an item as interest.
Good question, and I do not have a good answer.

It really would depend on how the `ItemManager` implementation handles the interest. If valuing an item for such implementation is affected by the interest, then yes. 

I'm gonna write a more generic doc like: "Decrements the interest". Whatever the interest is, it is up to the implementation.

2024-12-19 12:17 UTC, mustermeiszer commented on src/Holdings.sol
> +        item[poolId][itemId_] = Item(scId, assetId, valuation_, 0, 0);
One optimization and logic proposal: 

* make all interfaces of `IItemManager` use `(PoolId poolId, ShareClassId scId, ItemId itemid, ...)` 
* For `Holdings` -> `ItemId = AssetId`

2024-12-19 12:27 UTC, lemunozm commented on src/Holdings.sol
> +        item[poolId][itemId_] = Item(scId, assetId, valuation_, 0, 0);
I thought about that. That would mean that other items, such as Bonds, should also be per `scId`, are we ok with that I guess. 

Could be any issue if later we want to move, i.e. a Bond from one share class to another?

2024-12-19 20:24 UTC, ilinzweilin requested changes
🚀

2024-12-19 20:24 UTC, ilinzweilin commented on src/AccountingItemManager.sol
> +    constructor(address deployer) Auth(deployer) {}
``
```suggestion
    constructor(address ward) Auth(ward) {}
```

2024-12-19 20:24 UTC, ilinzweilin commented on src/AccountingItemManager.sol
> +    constructor(address deployer) Auth(deployer) {}
deployer can pass a different address as ward

2024-12-19 20:24 UTC, ilinzweilin commented on src/AccountingItemManager.sol
> +pragma solidity 0.8.28;
```suggestion
pragma solidity ^0.8.28; 
```

2024-12-19 20:24 UTC, ilinzweilin commented on src/AccountingItemManager.sol
> +pragma solidity 0.8.28;
I would always use caret to make sure that this certain version is used **or any higher**

2024-12-19 20:24 UTC, ilinzweilin commented on src/interfaces/IAccountingItemManager.sol
> +    }
struct is a very unflexible structure to go with imo, based on the discussion below.
Why not just having an array
 containing `AccountIds`. 
In that way we can stay flexible and provide different type & number of accounts for each item. 

We just need to make sure AccountId is unique across all account types. 
alternatively we can go with the following struct: 
```
struct Account {
        AccountId id;
        AccountType type; (can be an enum)
    }

```
and `Accounts` would be an array of the type `Account`

2024-12-19 20:24 UTC, ilinzweilin commented on src/AccountingItemManager.sol
> +    function itemAccounts(PoolId poolId, ItemId itemId) external view returns (Accounts memory) {
in theory this function is not required, as `accounts` is a public mapping and can be used as a getter

2024-12-19 20:24 UTC, ilinzweilin commented on src/AccountingItemManager.sol
having a separate contract and interface for `AccountingItemManager` feels a bit overengineered to me.
The logic is very tightly coupled to ItemManager and I would just merge that code into the ItemManager.

2024-12-19 20:24 UTC, ilinzweilin commented on src/interfaces/IItemManager.sol
> +    function itemValue(PoolId poolId, ItemId itemId) external view returns (uint128 value);
```suggestion
    function valuation(PoolId poolId, ItemId itemId) external view returns (uint128 value);
```

2024-12-19 20:24 UTC, ilinzweilin commented on src/interfaces/IItemManager.sol
> +    function valuation(PoolId poolId, ItemId itemid) external view returns (IERC7726);
```suggestion
    function oracle(PoolId poolId, ItemId itemid) external view returns (IERC7726);
```

2024-12-19 20:24 UTC, ilinzweilin commented on src/interfaces/IItemManager.sol
> +    function updateValuation(PoolId poolId, ItemId itemid, IERC7726 valuation) external;
```suggestion
    function updateOracle(PoolId poolId, ItemId itemid, IERC7726 valuation) external;
```

2024-12-19 20:24 UTC, ilinzweilin commented on src/interfaces/IItemManager.sol
> +    function update(PoolId poolId, ItemId itemId) external returns (int128 diff);
```suggestion
    function updateValuation(PoolId poolId, ItemId itemId) external returns (int128 diff);
```

2024-12-19 20:24 UTC, ilinzweilin commented on src/interfaces/IItemManager.sol
> +    function update(PoolId poolId, ItemId itemId) external returns (int128 diff);
I am not sure we need this function. 
Wouldn't the most recent valuation getter return the most recent valuation by calling the oracle?

2024-12-19 20:24 UTC, ilinzweilin commented on src/interfaces/IItemManager.sol
> +    function create(PoolId poolId, IERC7726 valuation, bytes calldata data) external;
```suggestion
    function create(PoolId poolId, IERC7726 oracle, bytes calldata data) external;
```

2024-12-19 20:24 UTC, ilinzweilin commented on src/Holdings.sol
> +    constructor(address deployer, IPoolRegistry poolRegistry_) AccountingItemManager(deployer) {
```suggestion
    constructor(address ward, IPoolRegistry poolRegistry_) AccountingItemManager(deployer) {
```

2024-12-19 20:24 UTC, ilinzweilin commented on src/Holdings.sol
> +    mapping(PoolId => mapping(ItemId => Item)) public item;
the more I look at the mappings with that naming structure, giving it a singular name instead of plural feels not intuitive to me.  
```
Item item = items[poolId][ItemId] -> intuitive
Item item = item[poolId][ItemId] -> not intuitive
```

I have never noticed any other solidity contracts using the singular naming & and we haven't in the past. Is there any reference?

I know I said in slack thatI don't have hard feelings, but now that I am reading through the code, I notice the difference...

2024-12-19 20:24 UTC, ilinzweilin commented on src/Holdings.sol
> +    function create(PoolId poolId, IERC7726 valuation_, bytes calldata data) external auth {
I would make sure that the poolId exists  & the oracle is a valid address

2024-12-19 20:24 UTC, ilinzweilin commented on src/Holdings.sol
> +        itemId[poolId][scId][assetId] = itemId_;
hmmm, maybe I am missing something, but why would an item be bound to a share class. Shouldn't the items be per pool and the share class NAVs etc are calculated on top.

2024-12-19 20:24 UTC, ilinzweilin commented on src/Holdings.sol
> +    uint128 assetAmountValue;
I think it wouldn't hurt to also store `poolId` and `itemId` info here. Since we don't have a mapping from `item -> poolId`. 

I am don't fully understand why we need `scId` here

2024-12-19 20:24 UTC, ilinzweilin commented on src/Holdings.sol
> +    mapping(PoolId => mapping(ItemId => Item)) public item;
since we are using increment for `itemId` of each pool here, we could simplify the mapping:
`mapping(PoolId => Item[]) public items;`

each poolId would return an array of items, where the index of each item is the itemId

2024-12-19 20:24 UTC, ilinzweilin commented on src/Holdings.sol
> +        delete item[poolId][itemId_];
are we sure that we want to delete item and not just flag closed

2024-12-19 20:24 UTC, ilinzweilin commented on src/Holdings.sol
> +        Item storage item_ = item[poolId][itemId_];
same here would make sure pool & item exist. Same applies for all the following functions

2024-12-19 20:24 UTC, ilinzweilin commented on src/Holdings.sol
> +    uint128 assetAmountValue;
why are we storing `assetAmountValue` that needs to be updated.
I think the valuation getter should just always return the most recent valuation from the oracle to avoid outdated data...

2024-12-19 20:24 UTC, ilinzweilin commented on src/Holdings.sol
> +        item_.assetAmountValue += amountValue;
I think only the `assetAmount` needs to be increased and the valuation just always retrieved from the oracle based on the `assetAmount`

2024-12-19 20:24 UTC, ilinzweilin commented on src/Holdings.sol
> +        return item[poolId][itemId_].valuation;
I would always return the exact valuation from the oracle here based on the asset amount of course: 
pseudo code:
`        return uint128(item_.valuation.getQuote(item_.assetAmount, item_.assetId), poolCurrency));`

2024-12-19 20:24 UTC, ilinzweilin commented on src/Holdings.sol
> +    function update(PoolId poolId, ItemId itemId_) external auth returns (int128 diff) {
can be removed imo

2024-12-19 20:24 UTC, ilinzweilin commented on src/Holdings.sol
> +        item_.assetAmountValue -= amountValue;
same here: think only the quantity needs to be increased and the valuation just always retrieved from the oracle based on the quantity

2024-12-20 09:28 UTC, mustermeiszer commented on src/interfaces/IItemManager.sol
> +    function update(PoolId poolId, ItemId itemId) external returns (int128 diff);
We need this definitely from a business perspective. This is actually updating the holdings if there has been a los or gain between now and the last update.

2024-12-20 09:29 UTC, mustermeiszer commented on src/Holdings.sol
> +        itemId[poolId][scId][assetId] = itemId_;
That is a business requirement. See PRD for details.

2024-12-20 09:30 UTC, mustermeiszer commented on src/Holdings.sol
> +    uint128 assetAmountValue;
We need that for knowing intermediate gains/loss.

2024-12-20 09:30 UTC, mustermeiszer commented on src/Holdings.sol
> +        delete item[poolId][itemId_];
Second that. Deleting seems dangerous to me ^^

2024-12-20 09:34 UTC, mustermeiszer commented on src/Holdings.sol
> +        item_.assetAmountValue += amountValue;
That is going to change. Increase will take into account an externally provided value for the given amount.  So that we can note how the item was priced when we got it. Note: This is in most cases not a synchronous composition, so that oracle value and purchase value can differ significantly.

2024-12-20 09:34 UTC, mustermeiszer commented on src/Holdings.sol
> +        item_.assetAmountValue -= amountValue;
See above.

2024-12-20 09:34 UTC, mustermeiszer commented on src/Holdings.sol
> +    function update(PoolId poolId, ItemId itemId_) external auth returns (int128 diff) {
Need that for sure for tracking loss/gains.

2024-12-20 14:56 UTC, ilinzweilin commented on src/Holdings.sol
> +    uint128 assetAmountValue;
yes, I am just suggesting having this wrapped into a getter function that always uses the most recent price from the oracle. 
The `assetAmountValue` can be outdated & if you need to update the value first it comes with a write / storage update operation which costs gas

2024-12-20 14:56 UTC, ilinzweilin commented on src/Holdings.sol
> +        itemId[poolId][scId][assetId] = itemId_;
can you point me to the section please

2024-12-20 19:29 UTC, lemunozm commented on src/Holdings.sol
> +        delete item[poolId][itemId_];
Curious, what's the security problem with deleting items from a map? (if deleting implies that the variable used to check their existence becomes 0). We'll never reuse that itemId

2024-12-20 21:58 UTC, mustermeiszer commented on src/Holdings.sol
> +        item[poolId][itemId_] = Item(scId, assetId, valuation_, 0, 0);
Yes, all items should be per share class. we can rather have a special share class that is the global one later.

2024-12-20 22:03 UTC, mustermeiszer commented on src/Holdings.sol
> +        itemId[poolId][scId][assetId] = itemId_;
https://www.notion.so/Centrifuge-Protocol-V1-1112eac24e178040bdfafb6a8e9b090c?pvs=4#1122eac24e178069aed7f3469d920c78

2024-12-20 22:04 UTC, mustermeiszer commented on src/Holdings.sol
> +    uint128 assetAmountValue;
How do you wanna calculate the gain/loss between last update and now, if you don't now the past value?

2024-12-27 12:45 UTC, lemunozm commented on src/Holdings.sol
> +        item[poolId][itemId_] = Item(scId, assetId, valuation_, 0, 0);
Ok

> For Holdings -> ItemId = AssetId

Just one thing regarding this. `ItemId` could be something different to `AssetId` in other `IItemManager` implementations, so it should be generic enough.  I think we will still need a mapping from `ItemId` => `AssetId`. So, changing this to use a `ShareClassId`, we're not saving us from the mapping. 

Anyways, I'm ok with using the `ShareClassId` param in `IItemManager` interface

2025-01-07 07:50 UTC, lemunozm commented on src/Holdings.sol
> +    function increase(PoolId poolId, ItemId itemId, uint128 amount) external auth returns (uint128 amountValue) {
Regarding this, let's start with your solution of having an extra parameter 👍🏻

2025-01-07 08:03 UTC, lemunozm commented on src/AccountingItemManager.sol
> +    constructor(address deployer) Auth(deployer) {}
@georgi had a strong opinion in favor of `deployer`. I'm ok with both names, but we should reach an agreement to use the same name for all contracts.

2025-01-07 08:08 UTC, lemunozm commented on src/AccountingItemManager.sol
> +pragma solidity 0.8.28;
I'm using the fixed version because, IIRC, @hieronx argued in favor of it for non-interfaces, but I do not remember now the exact reason. 

Again, I'm open to any approach as long as we have a consensus in all contracts to do the same

2025-01-07 08:42 UTC, lemunozm commented on src/interfaces/IAccountingItemManager.sol
> +    }
Yes, I think this makes sense. What we need to be sure of is that at least those 4 accounts exist for all `IItemManager` implementations. But we can model them as you say.

2025-01-07 08:57 UTC, lemunozm commented on src/AccountingItemManager.sol
The intention with it is that all `IItemManager` should share that logic. But I agree that maybe at this point feels like overengineering, so I agree, by now, to merge this with the `IItemManager` and put the implementation in the `Holdings` to let things simple. But probably we should factorize this part again later

2025-01-07 08:58 UTC, lemunozm commented on src/interfaces/IItemManager.sol
> +    function itemValue(PoolId poolId, ItemId itemId) external view returns (uint128 value);
The `valuation` name is the name we're using for `IERC7726`, which is different from the item value

2025-01-07 08:59 UTC, lemunozm commented on src/interfaces/IItemManager.sol
> +    function valuation(PoolId poolId, ItemId itemid) external view returns (IERC7726);
We already have "reached" consensus about these namings. In this case, valuation does not need to be an oracle; could be another contract that compute the value on-chain

2025-01-07 08:59 UTC, lemunozm commented on src/interfaces/IItemManager.sol
> +    function updateValuation(PoolId poolId, ItemId itemid, IERC7726 valuation) external;
Same as above

2025-01-07 08:59 UTC, lemunozm commented on src/interfaces/IItemManager.sol
> +    function create(PoolId poolId, IERC7726 valuation, bytes calldata data) external;
Same as above

2025-01-07 09:00 UTC, lemunozm commented on src/Holdings.sol
> +    constructor(address deployer, IPoolRegistry poolRegistry_) AccountingItemManager(deployer) {
Thread: https://github.com/centrifuge/pools-internal/pull/42#discussion_r1892983647

2025-01-07 09:03 UTC, lemunozm commented on src/Holdings.sol
> +    mapping(PoolId => mapping(ItemId => Item)) public item;
Agree with the mapping => array stuff.

Regarding the naming, I think it's something we need to discuss again in Slack, given we already reached a consensus about that

2025-01-07 09:04 UTC, lemunozm commented on src/Holdings.sol
> +    function create(PoolId poolId, IERC7726 valuation_, bytes calldata data) external auth {
Sure

2025-01-07 09:04 UTC, lemunozm commented on src/Holdings.sol
> +        delete item[poolId][itemId_];
@mustermeiszer

2025-01-07 09:06 UTC, lemunozm commented on src/Holdings.sol
> +        return item[poolId][itemId_].valuation;
Those are different values.`valuation.getQuote` returns the current value, here we're returning the valuation address used

2025-01-07 09:12 UTC, lemunozm commented on src/Holdings.sol
> +    mapping(PoolId => mapping(ItemId => Item)) public item;
Refs:
- slack thread: https://kflabs.slack.com/archives/C07PG2EUR9C/p1734423525896669
- PR where this was changed for poolRegistry: https://github.com/centrifuge/pools-internal/pull/45

2025-01-07 10:47 UTC, lemunozm commented on src/Holdings.sol
> +        item[poolId][itemId_] = Item(scId, assetId, valuation_, 0, 0);
@mustermeiszer I think this optimization can not be applied because we still need the mapping anyways. Also, because we still need the mapping, we can avoid passing the `ShareClassId` in all interface methods. I think this can be noisy for other `IItemManager` implementations, such as `Bonds`, where we would not need a `ShareClassId` parameter.

2025-01-07 11:30 UTC, mustermeiszer commented on src/Holdings.sol
> +        delete item[poolId][itemId_];
Never know what external integrations depend on this to be stable. Just safer and easier. Once defined, never used for something different than in the beginning.

2025-01-07 12:09 UTC, lemunozm commented on src/Holdings.sol
> +        delete item[poolId][itemId_];
I think we're talking about different things. Sure, a removed item would never be reused. Here, I'm just removing the item to save storage, but that ID will never be reused.

2025-01-07 14:06 UTC, mustermeiszer commented on src/Holdings.sol
> +        item[poolId][itemId_] = Item(scId, assetId, valuation_, 0, 0);
We would also need it for Bonds. All assets are either
* associated with ONE share class
* associated with ALL share classes

2025-01-07 15:22 UTC, lemunozm commented on src/Holdings.sol
> +        item[poolId][itemId_] = Item(scId, assetId, valuation_, 0, 0);
But don't we decide that the asset side could be agnostic from the `ShareClassId` here?

https://kflabs.slack.com/archives/C07PG2EUR9C/p1733859638266489?thread_ts=1733859377.513819&cid=C07PG2EUR9C

I'm not against adding this, but I want to be sure that adding the ShareClassId to the IItemInterface is not an extra layer that does not really need it.

2025-01-08 14:27 UTC, peculiarity commented on src/Holdings.sol
> +    mapping(PoolId => Item[]) public item;
**Note**: I would rename this to catalog. Catalog itself is a singular but it implies a collection of items. So for each `PoolId`, you have a list of items. Also not to mention that for a given `PoolId`  an array of items  is returned so in this case I don't think usage of `item` is the correct one.

2025-01-08 14:30 UTC, peculiarity commented on src/Holdings.sol
> +    mapping(PoolId => mapping(ShareClassId => mapping(AssetId => ItemId))) public itemId;
**Question**: 
Does this mapping exist for the sole purpose that you have a O(1) read  for getting a specific item instead of iterating over the array returned from the `item` variable and looking for one specific item?

2025-01-08 14:33 UTC, peculiarity commented on src/Holdings.sol
> +    mapping(PoolId => mapping(ItemId => mapping(uint8 kind => AccountId))) public accountId;
**Question**: 
I'm trying to understand how this is going to be used. I mean you populate the kind from the `accountId` so you know the accountId in advance. I assume you are going to read this mapping passing some sort of a `kind` but if that's the case can't you just pass directly the `accountId`?

2025-01-08 14:34 UTC, peculiarity commented on src/Holdings.sol
> +    constructor(address deployer, IPoolRegistry poolRegistry_) Auth(deployer) {
****Ultra NIT**:** Following CV side, the deployer address is always the last param.

2025-01-08 14:35 UTC, peculiarity commented on src/Holdings.sol
> +    function create(PoolId poolId, IERC7726 valuation_, AccountId[] memory accounts, bytes calldata data)
**Question:**
Any particular reason why `data` is not passed directly as `ShareClassId` , `AssetId` and instead it is passed as encoded calldata?

2025-01-08 14:38 UTC, peculiarity commented on src/Holdings.sol
> +        for (uint256 i = 0; i < accounts.length; i++) {
```suggestion
        for (uint256 i ; i < accounts.length; i++) {
```
It is a bad practice to initialize to 0. `uint256 i` is always 0 initially. Even during audits, this gets flagged.

2025-01-08 16:10 UTC, wischli commented on src/Holdings.sol
> +    bool alive;
Q: Wondering if keeping inactive items will rather be an edge-case or common practice in case we have an understanding of that currently.

2025-01-08 16:10 UTC, wischli commented on src/Holdings.sol
> +        poolRegistry = poolRegistry_;
CR: Missing check that `poolRegistry_ != address(0)`.

2025-01-08 16:10 UTC, wischli commented on src/Holdings.sol
> +        item_.alive = false;
Q: Curious on why we don't remove closed items from storage.

2025-01-08 16:10 UTC, wischli commented on src/interfaces/IItemManager.sol
> +    event ItemIncreased(PoolId indexed, ItemId indexed, IERC7726 valuation, uint128 amount, uint128 increasedValue);
Nit: Maybe make this more explicit? 

```suggestion
    event ItemIncreasedAmount(PoolId indexed, ItemId indexed, IERC7726 valuation, uint128 amount, uint128 increasedValue);
```

2025-01-08 16:10 UTC, wischli commented on src/types/ItemId.sol
> +    return ItemId.unwrap(itemId) - 1;
Nit: Maybe add a comment line that an item id is always >= 1

2025-01-08 16:50 UTC, peculiarity commented on src/Holdings.sol
> +        poolRegistry = poolRegistry_;
By default the value for the pooLRegistry is 0x0. Setting it to the zero address doesn't affect it that much.  Also usually in CV we avoid checking against the zero address ( there are some cases where you'd like to check ). The reason is that 0x0 address doesn't different much from any other address that is not the correct one.  What if I provide 0x1? Why 0x0 is so special and must be checked and 0x1 should not be ?

2025-01-08 16:51 UTC, peculiarity commented on src/Holdings.sol
> +        poolRegistry = poolRegistry_;
**Suggestion**.  Actually @wischli  made me thinking. I think it's a good idea to add a file method that can update the `poolRegistry` in here of wrong configuration / redeployment of the registry ( because of some reason ).

2025-01-08 16:53 UTC, peculiarity commented on src/Holdings.sol
> +        item_.alive = false;
@wischli  If you refer to using `delete`, then you can't use it with Custom Types. Also it doesn't "Delete" anything per se. It sets all non-mapping variables of the struct to their default value ( 0, "", false ... )

2025-01-09 08:00 UTC, lemunozm commented on src/Holdings.sol
> +    mapping(PoolId => Item[]) public item;
That's what I think at first, and I would expect:

```solidity
holdings.items(POOL_A)[index];
```

but from the test, I needed to call:

```solidity
holdings.item(POOL_A, index);
```
to retrieve the item. So it seems that when the element of the map is an array, the generated call retrieve the final element and we should follow the decision made. Unless I'm missing something

2025-01-09 08:03 UTC, lemunozm commented on src/Holdings.sol
> +    mapping(PoolId => mapping(ShareClassId => mapping(AssetId => ItemId))) public itemId;
The mapping exists because given a `(ShareclassId, AssetId)` pair you should identify an `ItemId`. This is needed, for example, in approveDeposit/Redemption methods

2025-01-09 08:04 UTC, lemunozm commented on src/Holdings.sol
> +    mapping(PoolId => mapping(ItemId => mapping(uint8 kind => AccountId))) public accountId;
The point here is that you must support different accounts for an item. So basically each item has a set of accounts, and each account of that set is identified by the `kind`

2025-01-09 08:08 UTC, lemunozm commented on src/Holdings.sol
> +    function create(PoolId poolId, IERC7726 valuation_, AccountId[] memory accounts, bytes calldata data)
Yes. `ShareClassId` and `AssetId` are specific to Holdings implementation. Other IItemManager will not use them. The IItemManager interface should be generic enough.

i.e. `Bonds` will use a collateral instead of those

2025-01-09 08:09 UTC, lemunozm commented on src/Holdings.sol
> +        for (uint256 i = 0; i < accounts.length; i++) {
Oh, didn't now that. 👍🏻 

> It is a bad practice to initialize to 0.

Is there any reason? Bloating code or so?

2025-01-09 08:16 UTC, lemunozm commented on src/Holdings.sol
> +    bool alive;
Here is the story about this. I'm still not super sure about array vs mapping for store items. For now I decided using an array.

The point is, if right now I'm using an array to store them, then I can not remove from the item array the closed items. I could clear them, but I'm not achieving nothing with that. So basically I can keep the old data as history for the UI (something similar we did in pallet-loans).

2025-01-09 08:20 UTC, lemunozm commented on src/Holdings.sol
> +        poolRegistry = poolRegistry_;
> The reason is that 0x0 address doesn't different much from any other address that is not the correct one.

Mostly agree with this reasoning.

From my point of view, we should check against 0 if something is treated as optional. So I would say 0x0 is special because it's always used as optional::none in a lot of cases. And that value could emerge automatically from reading a empty slot storage.

> add a file method

Correct, will add it 👍🏻

2025-01-09 08:21 UTC, lemunozm commented on src/Holdings.sol
> +        item_.alive = false;
Yes. More details here: https://github.com/centrifuge/pools-internal/pull/42#discussion_r1908328856

2025-01-09 08:25 UTC, lemunozm commented on src/interfaces/IItemManager.sol
> +    event ItemIncreased(PoolId indexed, ItemId indexed, IERC7726 valuation, uint128 amount, uint128 increasedValue);
You hint this to differentiate from the Interest, right?

Not sure about that 🤔. There is no something like IncreasedAmount vs IncreasedInterest. `ItemIncreased` is the general way, and `ItemIncreasedInterest` is a specific way of increasing it. It's more like top-down instead of being at the same level. 

But I will keep this idea in mind if I feel it's getting more confusing

2025-01-09 08:26 UTC, lemunozm commented on src/types/ItemId.sol
> +    return ItemId.unwrap(itemId) - 1;
Sounds good!

2025-01-09 08:34 UTC, lemunozm commented on src/Holdings.sol
> +        poolRegistry = poolRegistry_;
> add a file method

I'm rethinking this, and not sure if we should. We decided poolRegistry to be an immutable contract. It's supposed never to change, and if it finally changes, we should upload again the Holdings contract.

I will open a thread to discuss this among all of us. Not sure the decision to take.

2025-01-09 08:51 UTC, lemunozm commented on src/types/ItemId.sol
> +    return ItemId.unwrap(itemId) - 1;
Done

2025-01-09 08:51 UTC, lemunozm commented on src/Holdings.sol
> +    constructor(address deployer, IPoolRegistry poolRegistry_) Auth(deployer) {
Done

2025-01-09 08:56 UTC, peculiarity commented on src/interfaces/IItemManager.sol
> +    function accountId(PoolId poolId, ItemId itemId, uint8 kind) external view returns (AccountId);
Not sure where to put it but  you are missing the getter definions for the `item` and the `itemId` public variables.

2025-01-09 09:01 UTC, peculiarity commented on src/Holdings.sol
> +    mapping(PoolId => Item[]) public item;
Ah, right! Automatically generated getters don't return dynamic arrays.  Same like they don't return structs but rather tuples.  The way you call it is the correct one.  I would still rename it to a catalog but that's more of a **Suggestion**.  Given this comment and the one about missing getter definition in the interface, remember that it should return a tuple ( explicitly you have to define all members ). It cannot return the struct directly.r

2025-01-09 09:02 UTC, lemunozm commented on src/interfaces/IItemManager.sol
> +    function accountId(PoolId poolId, ItemId itemId, uint8 kind) external view returns (AccountId);
I think we do not need it, at list in the `IItemManager`, because they are related to the custom `Holding` implementation. Other `IItemManager` will have other structs to represent their items.

Maybe it makes more sense in `IHoldings`. Will think about it

2025-01-09 09:04 UTC, lemunozm commented on src/interfaces/IItemManager.sol
> +    function accountId(PoolId poolId, ItemId itemId, uint8 kind) external view returns (AccountId);
Maybe they should be private instead. At least the `item` array

2025-01-09 09:36 UTC, peculiarity commented on src/Holdings.sol
> +    function create(PoolId poolId, IERC7726 valuation_, AccountId[] memory accounts, bytes calldata data)
I see. For me this is more like a code smell. I see you have written documentation but you haven't provided explanation for each parameter. Here comes the tricky part. Lets say explain in the documentation if it's implemented by the Holding then the data is encoded `ShareClassId` and `AssetId`. 
Then there is another contract that implements it and you have to extend that documentation because let's face it, first `data` as param name is very generic and second the person who uses this interface must know what this param is used for.

My suggestion is to define this method as part of the final interface . i.e. IHoldings, IBonds with its specific definition. 

One more thing. **Super Nit** `create` somehow implies that something must be returned from the method. Suggestion would be to rename it to `addItemEntry` or `initializeItem`.

2025-01-09 09:40 UTC, peculiarity commented on src/interfaces/IItemManager.sol
> +    function accountId(PoolId poolId, ItemId itemId, uint8 kind) external view returns (AccountId);
I agree that they are not needed in the `ItemManager`  but rather in the `IHoldings`. I commented it here because `accountId` was alos a state variable in the `Holdings` contract but if they are public, definitely must be defined in the interface.

2025-01-09 09:43 UTC, peculiarity commented on src/libraries/MathLib.sol
> +    function toInt128(uint256 value) internal pure returns (int128) {
Nit: Test is missing

2025-01-09 09:44 UTC, lemunozm commented on src/Holdings.sol
> +    mapping(PoolId => Item[]) public item;
> remember that it should return a tuple ( explicitly you have to define all members )

Yeah, that sucks. Will think about the naming

2025-01-09 09:49 UTC, lemunozm commented on src/Holdings.sol
> +    function create(PoolId poolId, IERC7726 valuation_, AccountId[] memory accounts, bytes calldata data)
> My suggestion is to define this method as part of the final interface . i.e. IHoldings, IBonds with its specific definition

Do you mean define as part as `IHolding` interface, and later let the generic `IItemManager` method to be implemented calling the `IHolding` interface? I like that 👍🏻 .

> create somehow implies that something must be returned from the method.

I didn't thought about that implicit behavior through the `create()` name. But it could make sense. I'll think about it 👍🏻

2025-01-09 09:58 UTC, lemunozm commented on src/Holdings.sol
> +        poolRegistry = poolRegistry_;
Added

2025-01-09 10:07 UTC, lemunozm commented on src/Holdings.sol
> +        Item storage item_ = item[poolId][itemId_.index()];
@georgi, maybe you can help me with this.

I do not want these methods to return an indexOutOfBounds if the index is not in the array. Instead. I want them to return a `ItemNotFound` as the `IItemManager` dictates.

My first approach is:

```solidity
try item[poolId][itemId_.index()] returns (Item memory item_) {
    // Stuff
} catch Panic(uint236 0x32 /*oob*/) {
    revert(ItemNotFound())
}
```

Nevertheless, solidity forces me not to use `storage` and use `memory` instead. Any workaround you suggest?

2025-01-09 10:18 UTC, lemunozm commented on src/Holdings.sol
> +    function create(PoolId poolId, IERC7726 valuation_, AccountId[] memory accounts, bytes calldata data)
Added the `IHolding::create()` method. 

By now, I'm gonna let the `create()` name, given our inheritance of this name and the current understanding from all of us. I think if the method still creates something internally, even though it does not return stuff, the name is still valid IMO.

2025-01-09 10:29 UTC, peculiarity commented on src/Holdings.sol
> +        Item storage item_ = item[poolId][itemId_.index()];
`try / catch` doesn't support storage pointers as returned values

2025-01-09 10:29 UTC, peculiarity commented on src/Holdings.sol
> +        Item storage item_ = item[poolId][itemId_.index()];
Possible workaround IMO could be 
```
Item[] storage items = item[poolId];
require(items.length >= itemId_.index(), "NotFound");
Item storage item_ = items[itemId_.index()];
 ```

2025-01-09 10:31 UTC, peculiarity commented on src/Holdings.sol
> +    function create(PoolId poolId, IERC7726 valuation_, AccountId[] memory accounts, bytes calldata data)
Yeah, there are cases where `create` not necessarily have to return anything. I'm fine with how it is . Couldn't think of a better name anyways.

2025-01-09 10:40 UTC, lemunozm commented on src/Holdings.sol
> +        Item storage item_ = item[poolId][itemId_.index()];
Thanks!

2025-01-09 10:40 UTC, lemunozm commented on src/libraries/MathLib.sol
> +    function toInt128(uint256 value) internal pure returns (int128) {
Added

2025-01-09 10:41 UTC, lemunozm commented on src/Holdings.sol
> +        item_.alive = false;
After a conversation with Frederik, we do not need to remove items from Holdings, so I just remove the `alive` field. Everything is alive now 🌳

2025-01-09 10:43 UTC, lemunozm commented on src/interfaces/IItemManager.sol
> +    function accountId(PoolId poolId, ItemId itemId, uint8 kind) external view returns (AccountId);
Could be the case that they are public because you need to access them from the test, but they are not exposed through the interface?

2025-01-09 10:46 UTC, peculiarity commented on test/unit/libraries/MathLib.t.sol
> +    function testToInt128Overflow(int128 x) public {
I find this one:
```
 function testToInt128Overflow(uint256 x) public {
        x= bound(x, uint256(uint128(type(int128).max)) + 1 , type(uint256).max);
        vm.expectRevert(MathLib.Int128_Overflow.selector);
        MathLib.toInt128(x);
   }
```
simpler. 
Also the passed param is of type uint256  and you are testing (uint256 -> int128 ) conversion.

2025-01-09 10:49 UTC, lemunozm commented on src/interfaces/IItemManager.sol
> +    function accountId(PoolId poolId, ItemId itemId, uint8 kind) external view returns (AccountId);
Right now, I added `itemId()` getter through the interface with the autogenerated code, and I also have an `itemProperties(),` which only returns the relevant properties. Other properties can be considered internal at this point (could not be so in the future).

Does that make sense by now?

2025-01-09 10:56 UTC, lemunozm commented on test/unit/libraries/MathLib.t.sol
> +    function testToInt128Overflow(int128 x) public {
Makes sense! added your solution

2025-01-09 10:57 UTC, peculiarity commented on src/interfaces/IItemManager.sol
> +    function accountId(PoolId poolId, ItemId itemId, uint8 kind) external view returns (AccountId);
Well here is what bothers me. You have 3 separate view methods `itemProperties` , `itemValue`, `valuation` that basically return a value of specific property. 
If you define the getter in the interface for the `item` and return a specific `Item` then  I don't see the need of all these methods. 
I have the feeling that this is back to the discussion of having multiple getters and bloating the code vs just 1 getter that returns the `Item` and you can read any value you want. Wdyt?

2025-01-09 11:01 UTC, lemunozm commented on src/interfaces/IItemManager.sol
> +    function accountId(PoolId poolId, ItemId itemId, uint8 kind) external view returns (AccountId);
The problem here is that `itemValue()` and `valuation()` are generic methods from `IItemManager`. Each implementation should store or compute those values as they need. In different ways.

`itemProperties()` is specific from `IHoldings`.

The attributes from `Item` struct are private to how `Holdings` decide internally to store its data and should not be public. It can change, and we do not want to break the `Holdings` API. And definitelly, they are not shared across other `IItemManager` implementation

2025-01-09 11:02 UTC, peculiarity commented on src/Holdings.sol
> +        for (uint256 i = 0; i < accounts.length; i++) {
It's more of a gas thingy. It's already 0 so the assigning explicitly 0 adds some opcodes.

2025-01-09 11:16 UTC, lemunozm commented on src/Holdings.sol
> +        delete item[poolId][itemId_];
No longer applies because we do not support close()

2025-01-09 11:18 UTC, lemunozm commented on src/Holdings.sol
> +        for (uint256 i = 0; i < accounts.length; i++) {
Ok, I thought the optimizer automatically discarded these kind of things

2025-01-09 14:15 UTC, peculiarity commented on src/Holdings.sol
> +        itemId[poolId][scId][assetId] = itemId_;
**Question:** Isn't it supposed to have a check whether the given `poolId` has assigned the  `scId` in `ShareClassManager` ? Same goes with hte `assetID`

2025-01-09 14:48 UTC, lemunozm commented on src/Holdings.sol
> +        itemId[poolId][scId][assetId] = itemId_;
From the Holdings perspective, it's independent. The pool manager will check that probably before call `create()`, because the PoolManager has access to the `ShareClassId`

2025-01-09 14:55 UTC, lemunozm commented on src/Holdings.sol
> +    mapping(PoolId => Item[]) public item;
I prefer by now to leave `item`, let's see how to name this more accurately when we have other `IItemManager`

2025-01-09 15:57 UTC, lemunozm commented on src/Holdings.sol
> +        require(poolRegistry.exists(poolId), IPoolRegistry.NonExistingPool(poolId));
Thinking about this... given `Holdings.create()` needs to be called under the unlocked pool. We do not need to check for pool existence because it always exists. Probably, we do not need to check for pool existence anywhere given the current architecture precondition.

Would you remove the check? It seems like a basic check, but really it's not needed. It's the `PoolManager` duty from my PoV.

2025-01-09 16:04 UTC, lemunozm commented on src/Holdings.sol
> +        itemId[poolId][scId][assetId] = itemId_;
Discussed in the review thread

2025-01-13 16:20 UTC, wischli approved these changes
Stellar work 🚀🚀🚀 Thanks for answering all my nitty-gritty questions! Nothing to complain from my side.

2025-01-14 07:59 UTC, peculiarity approved these changes

2025-01-14 08:01 UTC, lemunozm commented on src/Holdings.sol
> +        require(poolRegistry.exists(poolId), IPoolRegistry.NonExistingPool(poolId));
Finally, I decided to remove the check. I think we should not add these checks in other contracts if by architecture they're not required right now

2025-01-14 10:28 UTC, ilinzweilin approved these changes

2025-01-14 11:13 UTC, mustermeiszer reviewed
Have a change request, and one note. Otherwise looks great!

2025-01-14 11:13 UTC, mustermeiszer commented on src/Holdings.sol
> +    mapping(PoolId => mapping(ItemId => mapping(uint8 kind => AccountId))) public accountId;
QUESTION

This replaces the fixed types (Gains, Loss, etc) with a variable amount, right?

2025-01-14 11:13 UTC, mustermeiszer commented on src/Holdings.sol
> +        amountValue = uint128(valuation_.getQuote(amount, AssetId.unwrap(item_.assetId), poolCurrency));
CR

We can not rely on the valuation here. This would need a separate contract to deployed that gives the right past value. Lets just use a fixed `D18` here.

2025-01-14 11:13 UTC, mustermeiszer commented on src/Holdings.sol
> +        amountValue = uint128(valuation_.getQuote(amount, AssetId.unwrap(item_.assetId), poolCurrency));
CR

See above.

2025-01-14 11:13 UTC, mustermeiszer commented on src/Holdings.sol
> +        emit AccountIdSet(poolId, itemId_, accountId_);
NIT

Should we allow to retreive the `kind` more easily in the event by making it a separate field?

2025-01-14 11:13 UTC, mustermeiszer commented on src/Holdings.sol
> +        return item[poolId][itemId_.index()].assetAmountValue;
NOTE

Can we also add one that is `itemAmount` so that if one would want to compute the latest value they could 

`let currentValue = IItemManager.itemAmount() * IItemManager.valuation()`

2025-01-14 12:06 UTC, lemunozm commented on src/Holdings.sol
> +        emit AccountIdSet(poolId, itemId_, accountId_);
No strong opinion. Maybe we're wasting an extra duplicated byte if we do so?

2025-01-14 12:06 UTC, lemunozm commented on src/Holdings.sol
> +        amountValue = uint128(valuation_.getQuote(amount, AssetId.unwrap(item_.assetId), poolCurrency));
Solved above.

2025-01-14 12:06 UTC, lemunozm commented on src/Holdings.sol
> +        amountValue = uint128(valuation_.getQuote(amount, AssetId.unwrap(item_.assetId), poolCurrency));
Solved in the sync. Outcome:
- We can have an IERC7726 implementation with transient storage to let the FM to set the price they want.
- Using IERC7726 everywhere allows also to use onChain computed values in the interface easily.

2025-01-14 12:06 UTC, lemunozm commented on src/Holdings.sol
> +    mapping(PoolId => mapping(ItemId => mapping(uint8 kind => AccountId))) public accountId;
Yeah you have 256 accounts per ItemId

2025-01-14 12:06 UTC, lemunozm commented on src/Holdings.sol
> +        return item[poolId][itemId_.index()].assetAmountValue;
Makes sense! Will do

2025-01-14 12:17 UTC, lemunozm commented on src/Holdings.sol
> +        emit AccountIdSet(poolId, itemId_, accountId_);
Maybe it makes sense if we want to index the kind

2025-01-14 12:23 UTC, lemunozm commented on src/Holdings.sol
> +        emit AccountIdSet(poolId, itemId_, accountId_);
Added

2025-01-14 12:24 UTC, merged