WIP. Portfolio contract impl
centrifuge/protocol-v3 pull request #5
Opened 2024-10-09 16:45 UTC by lemunozm

# Description

Fixes #2

For the `Portfolio` contract

- we want:
  - Handling the accounting of items: tracking how much debt is increased/decreased
  - Be able to value items/portfolios.
  - Be able to update items.
- we don't want:
  - Handling permissions.
  - Distinguish between kinds of items.

### Lifecycle of an item from a portfolio.
- `create()` -> collateral attached to the new created item
  - Any calls to: `increase()`/`decrease()`/`updates()`/...
- `close()` -> collateral detached from the item

**Blocked by:**
- https://github.com/centrifuge/asset-pools/pull/19
- https://github.com/centrifuge/asset-pools/pull/22

2024-10-09 16:51 UTC, lemunozm commented on src/Portfolio.sol
> +}
Here, I'm getting a unique address for our assets. I think with 20 bytes; we can not have collisions (otherwise, the own eth would not work)

2024-10-09 16:51 UTC, lemunozm commented on src/Portfolio.sol
> +type ItemId is uint32;
I feel this is quite useful for IDs (which do not require methods to manipulate them), but not sure about our rules regarding this

2024-10-10 07:14 UTC, wischli commented on src/Portfolio.sol
> +
One result of the `InterestAccrual` spec call was that the `Portfolio` contract is the entity to identify the rate group of an item such that `LinearAccrual` contract only needs to map a `Group` to a `Rate` : https://www.notion.so/Interest-Accrual-11a2eac24e1780eca702c117cbc487d1

```solidity
    enum CompoundingPeriod {
        Secondly,
        Daily,
        Quarterly,
        Biannually,
        Annually
    }
    
    struct Group {
        uint128 ratePerPeriod;
        CompoundingPeriod period;
    }

    struct Rate {
        // accumlated rate index over time (prev chi)
        uint128 accumulatedRate;
        // last time the rate was accumulated
        uint64 lastUpdated;
    }

    mapping(Group => Rate) public rates;
```

2024-10-10 07:14 UTC, wischli commented on src/Portfolio.sol
> +        bytes32 poolAdminRole = bytes32(uint256(PoolId.unwrap(poolId)));
I might be wrong but IIUC this is not collision resistant, ie it is possible to generate the same bytes for instance from an item id.

2024-10-10 07:44 UTC, hieronx commented on src/Portfolio.sol
> +    uint128 totalInterestPaid;
I don't think these are needed

2024-10-10 07:45 UTC, hieronx commented on src/Portfolio.sol
> +    uint64 maturity;
I dont think this is needed here

2024-10-10 07:45 UTC, hieronx commented on src/Portfolio.sol
> +    IERC7726 valuationMethod;
I would just call it
```suggestion
    IERC7726 valuation;
```

2024-10-10 08:12 UTC, peculiarity commented on src/Portfolio.sol
> +struct ItemInfo {
```suggestion
struct ItemMetadata {
```

2024-10-10 09:11 UTC, lemunozm commented on src/Portfolio.sol
> +
This comment is related to the usage of `RateId`? that we've discussed in slack, right?

2024-10-10 09:13 UTC, lemunozm commented on src/Portfolio.sol
> +        bytes32 poolAdminRole = bytes32(uint256(PoolId.unwrap(poolId)));
Why that? `PoolId` (uint64) is smaller than bytes32 (equivalent to uint256), so it always fits with no collision.

Anyways, this will be removed and use `Auth` instead.

2024-10-10 09:16 UTC, lemunozm commented on src/Portfolio.sol
> +    IERC7726 valuationMethod;
Maybe the `valuation()` method should be named differently then? To avoid confusion, because that method processes the result coming from this IERC7726 valuation, so both are differents

2024-10-10 09:19 UTC, lemunozm commented on src/Portfolio.sol
> +struct ItemInfo {
Just curious, could you rationalize it?

Not sure if metadata is just what we store there... 🤔

2024-10-10 13:02 UTC, hieronx commented on src/Portfolio.sol
> +
Add two methods:
```solidity
function nav(PoolId poolId) external view returns (uint128 value) {
  // Iterate over all items, call getQuote on each, sum all values and return this
}

function indicativeNav(PoolId poolId) external view returns (uint128 value) {
  // Iterate over all items, call getIndicativeQuote on each, sum all values and return this
}
```

2024-10-10 13:02 UTC, hieronx commented on src/Portfolio.sol
> +
Add `updateRate` and `updateValuation` methods

2024-10-11 10:47 UTC, lemunozm commented on src/Portfolio.sol
> +    }
From the Frederik specs, this method is divided into two, one for the return of the principal and another one for the interest.

Does it make sense to replicate that? I think the only difference is regarding the gas. Two more accurate calls vs one generic call. Depends on the likelihood of each scenario

2024-10-11 11:01 UTC, lemunozm commented on src/Portfolio.sol
> +
I'm wondering. To avoid using `getIndicateQuote()` and be more tied to ERC7726, could make sense to encode the "indicative" knowledge as part of the `base` part in `getQuote()`?

Right know we do: 
```solidity
address base = address(uint160(uint256(keccak256(abi.encode(collateral.source, collateral.id)))));
uint128 normalPrice = getQuote(1, base, currency)
uint128 indicativePrice = getIndicativeQuote(1, base, currency)
```

Could we do:
```solidity
enum PriceMode {
    Default
    Indicative
}

address base = address(uint160(uint256(keccak256(abi.encode(collateral.source, collateral.id, Default)))));
uint128 normalPrice = getQuote(1, base, currency)

address base = address(uint160(uint256(keccak256(abi.encode(collateral.source, collateral.id, Indicative)))));
uint128 indivativePrice = getQuote(1, base, currency)

2024-10-11 11:06 UTC, lemunozm commented on src/Portfolio.sol
> +
Later we can pass the same `PriceMode` enum to `nav()`

2024-10-11 11:17 UTC, hieronx commented on src/Portfolio.sol
> +
That just makes it more implicit. The main mistake I think we made on Centrifuge Chain with this was being implicit, when you were getting which price/NAV. I would really like to make it as explicit as possible now, to avoid incorrect usage. I think introducing a new method on the oracle side is fine for that, and helps the case.

2024-10-11 11:40 UTC, lemunozm commented on src/Portfolio.sol
> +    }
@hieronx I think at this contract level, `transferDebt()` is just exactly calling `decreaseDebt(from) + increaseDebt(to)`, so I think there is no reason to create such call. The top layer can offer this.

I mean, `transferDebt()` do not add any new information

2024-10-11 11:50 UTC, hieronx commented on src/Portfolio.sol
> +    }
It might be worth the gas cost though. But agreed it's worth considering. Once we have a more complete integrated system, we can write gas snapshot tests, and see.

2024-10-11 11:55 UTC, lemunozm commented on src/Portfolio.sol
> +        require(ok, CollateralCanNotBeTransfered());
I do not fully remember what was the latest decision regarding transferring the collateral in the Portfolio. Should be delegated to the higher level?

@hieronx @ilinzweilin

2024-10-11 11:58 UTC, lemunozm commented on src/Portfolio.sol
> +    }
Ok. By now, internally, I can not save any read/write operation by doing it in the same method

2024-10-11 11:59 UTC, lemunozm commented on src/Portfolio.sol
> +    }
But it's true that I need to check both amounts matches, so it deserves doing here the operation and checks. Never mind, we keep it!

2024-10-11 12:53 UTC, hieronx commented on src/Portfolio.sol
> +        require(ok, CollateralCanNotBeTransfered());
I think keep it in the portfolio for now, but we might move it out later.

2024-10-14 06:11 UTC, lemunozm commented on src/Portfolio.sol
> +        require(ok, CollateralCanNotBeTransfered());
Ok. If we keep it, we then require some logic in the `close()` method to return the collateral to the creator of the item and also store the creator's address.

2024-10-14 11:50 UTC, lemunozm commented
Ready for another review phase. 

Some points could require discussion:
- After some play around, I've decided to make the `increaseDebt()`/`decreaseDebt()` methods to accept an `amount` instead of a `quantity`. It makes life much easier later for transferring debt (which can be done directly). Also, the interface is more "friendly" I guess. The difference in achieving this is that the `getQuote()` method now receives the `base` and `quote` parameters interchanged. Still open to discussion and see how it evolves.

- Added a `creator` field to be able to return the collateral to the creator of the asset in the close() method.

- As we talked @Jeroen, I've added `getQuote` and `getIndicativeQuote()`. Nevertheless, later, for the usage in the `nav()`/`itemValuation()`, I'm using an enum to discriminate which underlying method to use and avoid duplicating the same code to just end up calling different a `getXXXQuote()` method. I hope you agree with it. 
  - If you still think we need to have an explicit method named as `indivativeNav()` to abstract from the enum indexes, then we could add a thin wrapper over `nav(PricingMode.Indicative)`.

- `owner` (understood as borrowed) removed from the `Item`. The next layer should handle this.

- Removed `PoolId` and `ItemId` types to not add extra noise now.

2024-10-14 17:29 UTC, hieronx commented
> Added a creator field to be able to return the collateral to the creator of the asset in the close() method.

I think you can just make this a parameter in the close method. Since this is anyways permissioned, a higher level contract can ensure it is the correct address.

This also allows building for example a liquidation layer on top, where the collateral is transferred to a different user than the initial creator.

2024-10-14 17:32 UTC, hieronx commented on src/Portfolio.sol
> +    error ItemNotFound();
Let's move events and errors to the interface

2024-10-14 17:33 UTC, hieronx commented on src/Portfolio.sol
> +    IPoolRegistry poolRegistry;
Both should have the `public` modifier

2024-10-14 17:33 UTC, hieronx commented on src/Portfolio.sol
> +    constructor(address owner, IPoolRegistry _poolRegistry, ILinearAccrual _linearAccrual) Auth(owner) {
Should have postfixed underscore, not prefixed. Why: our style guide is that we use prefixed underscore for internal variables, and postfixed underscore for avoiding variable shadowing (like we have here, where the names otherwise match)

2024-10-14 17:34 UTC, hieronx commented on src/Portfolio.sol
> +        this.decreaseDebt(poolId, fromItemId, principal, interest);
Adding `this` makes it an external call, which makes it more expensive. Instead these 2 methods should be `public` rather than `external`, and then `this.` should be removed

2024-10-14 17:35 UTC, hieronx commented on src/Portfolio.sol
> +function exists(Item storage item) view returns (bool) {
Imo this is very rusty solidity ;) I admit it is more stylistic, but I would have an internal method `_doesItemExist` (or something like that, or if it's one line like here, actually just put it inline.

2024-10-14 17:36 UTC, hieronx commented on src/Portfolio.sol
> +        uint128 amount = principal + interest;
Seems like this definition is not really required since it's only used once, can just be inline on L173

2024-10-14 17:38 UTC, hieronx commented on src/Portfolio.sol
> +        bool ok = item.info.collateral.source.transfer(item.info.creator, item.info.collateral.id, 1);
I would move the `transfer` to after the `delete` call, to prevent any reentrancy issues. See Solidity re-entrancy and the "checks-effects-interactions (CEI) pattern"

2024-10-14 18:33 UTC, lemunozm commented on src/Portfolio.sol
> +    IPoolRegistry poolRegistry;
Ok. Curious why. Is it intended to be accessible from other contracts that access the `Portfolio`?

2024-10-14 18:38 UTC, lemunozm commented on src/Portfolio.sol
> +    error ItemNotFound();
Ok, that's a question I had. It is supposed that I need to create an `IPortfolio` then.

Because with solidity you can create any contract with any method that matches, not fully sure when an interface is needed. For example, the `Pools` contract could have on top of its file the following:

```solidity
contract Portfolio {
    function nav() extend returns (uint128);
}
```
And I do not need to create a portfolio interface to call `nav()`

2024-10-14 18:39 UTC, lemunozm commented on src/Portfolio.sol
> +        this.decreaseDebt(poolId, fromItemId, principal, interest);
Ok, thanks for the declaration, I did not fully understand why, for some methods, I needed `this`. Now it makes sense!

2024-10-14 18:39 UTC, lemunozm commented on src/Portfolio.sol
> +function exists(Item storage item) view returns (bool) {
Ok, I wanted to encapsulate in a method because it's not a super simple line, and maybe in the future how we identify a "null" item change. So, let's go with `_doesItemExist()` 👍🏻

2024-10-14 18:39 UTC, lemunozm commented on src/Portfolio.sol
> +        uint128 amount = principal + interest;
Is there any cost for the EVM machine (plus optimizations) on declaring internal function variables?

2024-10-14 18:40 UTC, lemunozm commented on src/Portfolio.sol
> +        bool ok = item.info.collateral.source.transfer(item.info.creator, item.info.collateral.id, 1);
Thanks! I still do not have a sharp eye to realize these things

2024-10-14 18:40 UTC, lemunozm commented
> I think you can just make this a parameter in the close method. Since this is anyways permissioned, a higher level contract can ensure it is the correct address.

Makes sense! I guess the same can be done for `create()`. We can pass the creator address from where the asset belongs, right? As far as the `creator` has approved the transfer for the caller to `create()`, it will work.

2024-10-14 19:20 UTC, hieronx commented on src/Portfolio.sol
> +    error ItemNotFound();
A common style (and one we follow) is to create an interface file for every single contract, and put all the events, errors, and natspec comments per function here. See for example this: https://github.com/centrifuge/liquidity-pools/blob/main/src/interfaces/IInvestmentManager.sol

Benefits of this approach is:
- Keeps the core contract as simple as possible
- Allows having extensive natspec separately, that will be included in UIs etc
- Allows integrators to pull in the interface with all the documentation, for any version, while we hardcode the contract version

2024-10-14 19:21 UTC, hieronx commented on src/Portfolio.sol
> +    IPoolRegistry poolRegistry;
1. There is not really any downside to making a variable public.
2. It is helpful to be able to inspect dependencies, for many reasons. One is simply for us to build fork tests that check the dependencies are wired correctly.

2024-10-14 19:21 UTC, hieronx commented on src/Portfolio.sol
> +        this.decreaseDebt(poolId, fromItemId, principal, interest);
I think you should never need `this`. Although I might miss some case

2024-10-14 19:23 UTC, hieronx commented on src/Portfolio.sol
> +        uint128 amount = principal + interest;
Probably minimal, this is more of a subjective opinion from my side, but I'd argue a separate variable only makes sense if it's either:
- Used multiple times
- Not intuitive what the definition of the contents of the variable is.

In this case, imo defining it as `amount` doesn't actually make it clearer.

2024-10-14 19:25 UTC, hieronx commented
> We can pass the creator address from where the asset belongs, right? As far as the creator has approved the transfer for the caller to create(), it will work.

The approval should be to the portfolio contract actually, not to the creator.

2024-10-14 19:59 UTC, lemunozm commented on src/Portfolio.sol
> +    error ItemNotFound();
Thanks for the detailed explanation!

2024-10-14 20:01 UTC, lemunozm commented on src/Portfolio.sol
> +        this.decreaseDebt(poolId, fromItemId, principal, interest);
I guess `this` also changes the caller's context, so `msg.sender` will be the same contract address (?)

2024-10-14 20:09 UTC, lemunozm commented on src/Portfolio.sol
> +    }
I am not fully sure about our style of putting structs/enums in/out from contracts/interfaces. 

Here, I think I'm forced because `ItemInfo` belongs to the interface, so it's the only way to access `ItemInfo` from here (if not, I do not know how).

2024-10-14 20:09 UTC, lemunozm commented on src/Portfolio.sol
> +        bool ok = info.collateral.source.transferFrom(creator, address(this), info.collateral.id, 1);
> The approval should be to the portfolio contract actually, not to the creator.

Regarding this comment, I do not fully understand it. AFAIK, `transferFrom` can transfer  the tokens if `creator` has approved some amount of `collateral.id` (aka `1`) for `msg.sender`. Is that wrong?

2024-10-14 20:21 UTC, hieronx commented on src/Portfolio.sol
> +        bool ok = info.collateral.source.transferFrom(creator, address(this), info.collateral.id, 1);
Some `sender` gives an approval for `receiver` to transfer `amount` tokens on their behalf. Setting `allowance[sender][receiver] += amount`.

Then `spender` can call `transferFrom` with `from=sender`, where it checks `allowance[from][msg.sender]`.

If user A gives approval for user B to spend tokens, and B calls the portfolio contract, the portfolio contract cannot actually call `transferFrom` with `from=A` since it will check the allowance of `allowance[from][PortfolioContract]`, which is 0.

So the user is approving the portfolio contract, not the caller of the portfolio contract, to transfer the collateral.

2024-10-15 03:27 UTC, lemunozm commented on src/Portfolio.sol
> +        bool ok = info.collateral.source.transferFrom(creator, address(this), info.collateral.id, 1);
> since it will check the allowance of allowance[from][PortfolioContract]

Not sure why you set the `PortfolioContract` account in the allowance. Looking at the code, it seems to work as follows:

1. User A gives approval for user B:
  - `allowance[A][B] = 1`
2. User B calls `create()`using A as a `creator`:
  - `transferFrom(A, address(Portfolio))` and `B = msg.sender`, which under the hood it checks if `allowance[A][msg.sender] >= 1` that is `allowance[A][B] >= 1` which matches with the given approval above. No `PortfolioContract` address is used in the allowance mapping.
  
Am I blind? 🤔

2024-10-15 06:16 UTC, hieronx commented on src/Portfolio.sol
> +        bool ok = info.collateral.source.transferFrom(creator, address(this), info.collateral.id, 1);
The portfolio contract calls the ERC6909 contract, so
```
which under the hood it checks if allowance[A][msg.sender] >= 1 that is allowance[A][B] >= 1 
```

is instead
```
which under the hood it checks if allowance[A][msg.sender] >= 1 that is allowance[A][address(Portfolio)] >= 1 
```

since the `msg.sender` from the perspective of the ERC6909 contract is the Portfolio contract.

2024-10-15 06:37 UTC, lemunozm commented on src/Portfolio.sol
> +        bool ok = info.collateral.source.transferFrom(creator, address(this), info.collateral.id, 1);
Right! That's correct! I still do not internalize that each call done to a new contract changes the `sender`. This is quite different from Substrate.

Basically, that means that the `allowance` feature from `IERC6909` lost most of its potential because of this 😞. So, you use ERC6909 directly, or you can not delegate to other accounts through contracts

2024-10-15 07:17 UTC, hieronx commented on src/Portfolio.sol
> +        bool ok = info.collateral.source.transferFrom(creator, address(this), info.collateral.id, 1);
Indeed. The allowance is really intended as the main smart contract pattern for token transfers, not for delegating token approval to other users.

2024-10-16 09:03 UTC, wischli reviewed
Loving the return of mocks already in your first code PR! A few questions, mostly to "Solidity experts" from my side and a few nits.

Great documentation in the `IPortfolio`. A minor nit there: A few function params are missing docs.

Looking forward to seeing your tests!

2024-10-16 09:03 UTC, wischli commented on src/interfaces/IPortfolio.sol
> +    event InterestRateUpdated(uint64 indexed poolId, uint32 itemId, bytes32 rateId);
We are also dispatching a `RateAccumulated` event after updating the rate. Suppose both events can co-exist because `LinearAccrual` doesn't know about pool or item ids. Just wanted to point that out in case the `LinearAccrual` one can be removed due to being redundant.

2024-10-16 09:03 UTC, wischli commented on src/Portfolio.sol
> +        uint32 itemId = uint32(items[poolId].length);
Question towards Solidity experts: Curious if we can assume such casting to be safe.

2024-10-16 09:03 UTC, wischli commented on src/Portfolio.sol
> +        emit Create(poolId, itemId, info.collateral);
Nit question: AFAIU, events should still have some prefix/suffix related to the contract (e.g. `PortfolioCreated` or `NewPortfolio`) to make them unique in contrast of how we did it in Substrate where that was redundant.

2024-10-16 09:03 UTC, wischli commented on src/Portfolio.sol
> +        item.info.valuation = valuation;
Question for solidity experts: Curious if it makes more sense to move this repetitive pattern to a modifier? Especially since some functions such as this one only mutate one field of the unterlying `Item` struct such that we can save some gas by not declaring the entire item as `storage` but only the field.

```diff
- Item storage item = items[poolId][itemId];
+ IERC7726 storage valuation = items[poolId][itemId].valuation;
```

2024-10-16 09:03 UTC, wischli commented on src/Portfolio.sol
> +        emit DebtDecreased(poolId, itemId, principal, interest);
Curious why for `DebtIncreased` event we don't include the principal but for `DebtDecreased` we do.

2024-10-16 09:03 UTC, wischli commented on src/Portfolio.sol
> +        require(ok, CollateralCanNotBeTransfered());
Nit: In case the transfer fails, we can save minor gas by checking before deleting
```suggestion
        bool ok = collateral.source.transfer(collateralOwner, collateral.id, 1);
        require(ok, CollateralCanNotBeTransfered());
        
        delete items[poolId][itemId];
```

2024-10-16 09:03 UTC, wischli commented on src/Portfolio.sol
> +        require(_doItemExists(item), ItemNotFound());
Nit related to my above question of replacing the repetitive check with a modifier: If `_doItemExists` did not require `item` to be `storage`, then this view function could declare it as `memory` instead as we don't perform mutation; and same in `function nav`. But maybe irrelevant because we don't care too much for `view` functions.

2024-10-16 09:03 UTC, wischli commented on src/libraries/Decimal18.sol
> +pragma solidity 0.8.28;
Nit
```suggestion
pragma solidity ^0.8.28;
```

2024-10-16 09:03 UTC, wischli commented on test/unit/Portfolio.t.sol
> +contract MockERC6909 is IERC6909 {
Comment which can immediately be resolved: The Substrate mockbuilder rises from its ashes looking much **solid** 🚀

2024-10-16 09:16 UTC, lemunozm commented on src/Portfolio.sol
> +        emit Create(poolId, itemId, info.collateral);
Is it true even if the event belongs to an interface? The interface puts some kind of namespace. Here, I can use them without the namespace because I'm inheriting from that interface, but from the outside, I need to write `IPortfolio.Create`

2024-10-16 09:16 UTC, lemunozm commented on src/interfaces/IPortfolio.sol
> +    event InterestRateUpdated(uint64 indexed poolId, uint32 itemId, bytes32 rateId);
`InterestRateUpdated` is dispatched when `Portfolio` calls `renormalizedDebt()`, so I think in this path, there is no such collision.

2024-10-16 09:19 UTC, lemunozm commented on src/Portfolio.sol
> +        item.info.valuation = valuation;
I also thought about this. 

If I move `_doItemExists()` as a modifier. I would need to access the item there and also later in the function body. So 2 reads from the item from the storage

Anyways, I'm interested to know exactly when to use a modifier and when to use a simple call to a private method in the body of the function. Seems like it's exactly identical in most cases (and the same amount of code factorized), and sometimes the code under modifiers seems more tricky to follow (?)

2024-10-16 09:20 UTC, wischli commented on src/interfaces/IPortfolio.sol
> +    event InterestRateUpdated(uint64 indexed poolId, uint32 itemId, bytes32 rateId);
Perfect, then no collision or redundancy as `ILinearAccrual.RateAccumulated` is dispatched during rate update after periods have passed.

2024-10-16 09:28 UTC, lemunozm commented on src/Portfolio.sol
> +        emit DebtDecreased(poolId, itemId, principal, interest);
`increase` and `decrease` are not identical. 

When you increase, you just "borrow" money, if later that debt is added as an amount to the account. So basically, i.e. you ask for money because you want to buy your house, so now you have a debt.

Later, when you decrease, you can "pay" or "return" 2 kinds of amounts: the principal (the amount related to what you increased or borrowed) and the interest accrued over the time you had that money. Depending on what amount is returned for decreasing the debt, the accounting will behave differently.

So basically, there is no concept of principal when increasing because everything is principal. But note that `DebtIncreased` still register the amount used to increase.

2024-10-16 09:31 UTC, lemunozm commented on src/Portfolio.sol
> +        require(ok, CollateralCanNotBeTransfered());
I had a previous comment from Jeroen asking me to do it in the other way due to re-entrance issues and follow the CEI pattern 😆 : https://github.com/centrifuge/asset-pools/pull/5#discussion_r1799874965

2024-10-16 09:34 UTC, lemunozm commented on src/Portfolio.sol
> +        require(_doItemExists(item), ItemNotFound());
Not sure if I follow your comment correctly. `storage` is faster than `memory` though. Basically AFAIK ref vs copy, so `storage` is faster.

2024-10-16 09:34 UTC, lemunozm commented on src/libraries/Decimal18.sol
> +pragma solidity 0.8.28;
Good point

2024-10-16 09:38 UTC, lemunozm commented on test/unit/Portfolio.t.sol
> +contract MockERC6909 is IERC6909 {
Yeah, that's cool! Although I still miss some kind of closure for giving different implementations for each test case.

2024-10-16 10:05 UTC, hieronx commented on src/Portfolio.sol
> +        uint32 itemId = uint32(items[poolId].length);
We should probably add a `MAX_ITEMS` constant that limits the total number of items to `type(uint32).max` on `create()`, and then we can safely cast it here

2024-10-16 10:06 UTC, hieronx commented on src/Portfolio.sol
> +        emit Create(poolId, itemId, info.collateral);
Events are generally closely tied to the contract, so you don't need to add a prefix for the contract.

2024-10-16 10:07 UTC, hieronx commented on src/Portfolio.sol
> +        item.info.valuation = valuation;
If you use a modifier, the code is repeated inline in every place, so the bytecode size grows by the number of usages of the modifier. An internal method instead is not repeated in every place.

2024-10-16 10:07 UTC, hieronx commented on src/Portfolio.sol
> +        item.info.valuation = valuation;
The pattern I've seen most codebases use is to limit modifiers to access/authorization related checks, and use internal methods to everything else.

2024-10-16 10:08 UTC, hieronx commented on src/libraries/Decimal18.sol
> +pragma solidity 0.8.28;
Generally it's considered better practice to hardcode a specific Solidity version. That is also what we did in liquidity-pools.

2024-10-16 10:25 UTC, lemunozm commented on src/Portfolio.sol
> +        uint32 itemId = uint32(items[poolId].length);
Makes sense. Also, good catch William. In substrate, lengths could not be longer than `uint32`, but here, we could exceed that.

2024-10-16 10:26 UTC, lemunozm commented on src/Portfolio.sol
> +        item.info.valuation = valuation;
Thanks! Super accurate explanation in two sentences!

2024-10-16 10:28 UTC, lemunozm commented on src/libraries/Decimal18.sol
> +pragma solidity 0.8.28;
But for libraries/interfaces is it also true?

2024-10-16 12:31 UTC, ilinzweilin requested changes

2024-10-16 12:31 UTC, ilinzweilin commented on src/Portfolio.sol
> +        linearAccrual = linearAccrual_;
we need an auth `file` function where we can update the linearAccrual contract in case we swap it

2024-10-16 12:31 UTC, ilinzweilin commented on src/Portfolio.sol
> +        bool ok = info.collateral.source.transferFrom(collateralOwner, address(this), info.collateral.id, 1);
I would not create local variables that are only used once...
Unfortunately in makes the code less readable, but safes gas

2024-10-16 12:31 UTC, ilinzweilin commented on src/Portfolio.sol
> +        uint32 itemId = uint32(items[poolId].length);
I think , we also should always use `MathLib` or OpenZepplin `SafeCast` functions for casting though. 
Same as we are doing inside `liquidity-pools` https://github.com/centrifuge/liquidity-pools/blob/main/src/InvestmentManager.sol#L65

2024-10-16 12:31 UTC, ilinzweilin commented on src/Portfolio.sol
> +    function create(uint64 poolId, ItemInfo calldata info, address collateralOwner) external auth {
I think there might be items, like cash / fee items that are not bind to a collateral.
That's why I would move the locking function outside of `create` into a separate `lock` function. 
Within create: if a collateral id is provided, I would check if the collateral is locked in order to create the item. If no collateral id is provided, I would create the item without collateral.
I also think that we should be locking the collateral nfts in a seperate escrow contract.

2024-10-16 12:46 UTC, hieronx commented on src/Portfolio.sol
> +    function create(uint64 poolId, ItemInfo calldata info, address collateralOwner) external auth {
I think this is a good idea! 

For the last line, @lemunozm you can use this contract: https://github.com/centrifuge/liquidity-pools/blob/main/src/Escrow.sol

2024-10-16 12:48 UTC, wischli commented on src/Portfolio.sol
> +        emit DebtDecreased(poolId, itemId, principal, interest);
Thanks for the thorough explanation, makes perfect sense!

2024-10-16 13:03 UTC, lemunozm commented on src/Portfolio.sol
> +        bool ok = info.collateral.source.transferFrom(collateralOwner, address(this), info.collateral.id, 1);
I thought compiling with some minimal optimization level solved those kinds of things:

https://docs.soliditylang.org/en/latest/internals/optimizer.html#commonsubexpressioneliminator

> All subexpressions that are identifiers themselves are replaced by their current value if the value is an identifier.

which I would say, it's true for `ok`

2024-10-16 13:11 UTC, lemunozm commented on src/Portfolio.sol
> +    function create(uint64 poolId, ItemInfo calldata info, address collateralOwner) external auth {
> I think there might be items, like cash items that are not bind to a collateral.

Makes sense! 

> If no collateral id is provided, I would create the item without collateral.

Does it mean that I should model that as `collateral.source = address(0)`? That would mean that later we can not get the `quote`. Although I guess this does not affect because cash items are valued just with the debt (what Jeroen said in some meeting/thread)

> That's why I would move the locking function outside of `create` into a separate `lock` function.

Could you extend it? Not sure I'm following you with the `lock` part

2024-10-16 13:11 UTC, lemunozm commented on src/Portfolio.sol
> +        linearAccrual = linearAccrual_;
Need to dive into this 👍🏻

2024-10-16 14:15 UTC, hieronx commented on src/Portfolio.sol
> +    function create(uint64 poolId, ItemInfo calldata info, address collateralOwner) external auth {
> Does it mean that I should model that as collateral.source = address(0)? Does would mean that later we can not get the quote. Although I guess this does not affect because cash items are valued just with the debt (what Jeroen said in some meeting/thread)

Yeah exactly.

> Could you extend it? Not sure I'm following you with the lock part

I think the idea would be something like
```solidity
function lock(address collateral, uint256 id) external auth {
  // Transfer collateral to escrow
}

function create(address collateral, uint256 id, ..) external auth {
  // If not 0, check collateral is locked in escrow
  // Create item
}
```

2024-10-16 18:50 UTC, hieronx commented on src/libraries/Decimal18.sol
> +pragma solidity 0.8.28;
For interfaces, we intentionally specify a much more open version, since any integrators need to match the version range. So in liquidity pools we specify >=0.5.0: https://github.com/centrifuge/liquidity-pools/blob/main/src/interfaces/IInvestmentManager.sol#L2

For libraries, I think the same applies, that hardcoding a specific version is better for security.

2024-10-18 08:53 UTC, lemunozm commented on src/Portfolio.sol
> +    function create(uint64 poolId, ItemInfo calldata info, address collateralOwner) external auth {
Rewarding the escrow contract, do we expect a custom implementation of such contract? The liquidity pools one only handles ERC20, but here, we want to use ERC6909

2024-10-18 10:14 UTC, lemunozm commented on src/Portfolio.sol
> +    }
Do I need for this:
- Move it to `IPortfolio`?
- Create a custom error instead of revert?
  - And move it probably to `IPortfolio`
- Put the File event in `IPortfolio`?

If yes, what are the advantages?

2024-10-21 10:55 UTC, lemunozm commented on src/libraries/Decimal18.sol
> +pragma solidity 0.8.28;
This is fixed in https://github.com/centrifuge/asset-pools/pull/19, which should be merged first

2024-10-21 13:14 UTC, lemunozm commented on src/Portfolio.sol
> +    function create(uint64 poolId, ItemInfo calldata info, address collateralOwner) external auth {
Implemented as a separate PR: https://github.com/centrifuge/asset-pools/pull/22

Please avoid to review the current Escrow contract of this PR

2024-10-25 14:56 UTC, peculiarity commented on src/interfaces/IPortfolio.sol
> +        /// @dev Underlaying call to `ERC6909.getIndicativeQuote()`
There are no such methods defined in the ERC6909 spec or impl. 
What exactly is this supposed to do ?

2024-10-25 14:58 UTC, peculiarity commented on src/interfaces/IPortfolio.sol
> +    event Create(uint64 indexed poolId, uint32 itemId, IERC6909 source, uint256 tokenId);
```suggestion
    event Created(uint64 indexed poolId, uint32 itemId, IERC6909 source, uint256 tokenId);
```

2024-10-25 15:00 UTC, peculiarity commented on src/libraries/MathLib.sol
> +    function toUint32(uint256 value) internal pure returns (uint32) {
Some tests are missing I see :)

2024-10-25 15:04 UTC, lemunozm commented on src/interfaces/IPortfolio.sol
> +        /// @dev Underlaying call to `ERC6909.getIndicativeQuote()`
I wrote ERC6909 in the comment but I wanted to write ERC7726 xD

2024-10-25 15:28 UTC, lemunozm commented on src/interfaces/IPortfolio.sol
> +        /// @dev Underlaying call to `ERC6909.getIndicativeQuote()`
Fixed

2024-10-25 15:28 UTC, lemunozm commented on src/interfaces/IPortfolio.sol
> +    event Create(uint64 indexed poolId, uint32 itemId, IERC6909 source, uint256 tokenId);
Fixed

2024-10-25 15:28 UTC, lemunozm commented on src/libraries/MathLib.sol
> +    function toUint32(uint256 value) internal pure returns (uint32) {
Added

2024-10-25 19:16 UTC, peculiarity commented on src/Portfolio.sol
> +    }
Yes to all of them.
1. I think we talked about that :)
2. Having strings is pretty expensive because the string must be encoded into the bytecode and you pay shit ton of gas for non-zero byte. ( if it's like with the calldata, then for zero-byte you pay 4 gas and for non-zero 16 gas. ) When you have custom error, actually all you have is 4 bytes of the hashed signature and that's it .
3. We put events in interfaces.

2024-10-25 19:20 UTC, peculiarity commented on src/interfaces/Common.sol
> +interface IERC6909 {
Probably all of these Interfaces  will be already defined. IERC7726 could be in a separate file. Doesn't see much benefit of hacking multiple interfaces defined in this file. What does common mean ? What defines an interfaces being common?

2024-10-25 19:21 UTC, peculiarity commented on src/interfaces/IPortfolio.sol
> +        /// @notice Valuation used for this item.
Probably it's nice to write that this will be an address to an oracle providing valuation.

2024-10-25 19:21 UTC, peculiarity commented on src/libraries/MathLib.sol
> +            revert("MathLib/int128-overflow");
Let's move to custom errors ;)

2024-10-25 20:13 UTC, peculiarity commented on src/Portfolio.sol
> +        uint256 uniqueItemId = uint256(poolId) << 64 + itemId;
That's pretty clever but...
`uint256(poolId) << 64 + itemId` != `(uint256(poolId) << 64) + itemId`
and I'm pretty sure you want to have the second one :D

2024-10-25 20:27 UTC, peculiarity commented on src/Portfolio.sol
> +        uint256 uniqueItemId = uint256(poolId) << 64 + itemId;
Even though it is more expensive by some 26 gas I would suggest using `abi.encodePacked(poolId, itemId)`
This will give you in total 96 bytes. 
From left to right, first 64 bytes will be for the `poolId` and the following 32 bytes will be for the `itemId`. Which can be casted to `uint96`.
`uint96(bytes12(abi.encodePacked(poolId, itemId))`

Even if you decide to go with your implementation, I'm not sure why you shift by `64`and not `32`. You want to make space for the `itemId`'s 32 bytes, right? The way you do it, you leave 32 bytes empty. 
So you final number of 256 will consist.
 - 128 empty bytes
 - 64 bytes pool id ( at most )
 - 32 empty bytes
 - 32 bytes item id ( at most )

2024-10-25 21:04 UTC, peculiarity commented on src/Portfolio.sol
> +struct Item {
Move it to the `IPortfolio` interface ;)

2024-10-25 21:05 UTC, peculiarity commented on src/Portfolio.sol
> +    uint160 collateralId;
Is there a situation where you can have an item with `collateralId` == 0 ?

2024-10-25 21:11 UTC, peculiarity commented on src/Portfolio.sol
> +    function create(uint64 poolId, ItemInfo calldata info, IERC6909 source, uint256 tokenId) external auth {
I think the name is a little bit misleading.
You don't create anything (well probably the first time);
You put new item into the same `poolId`.
Suggestion: `addItem`, `add`

2024-10-25 21:23 UTC, peculiarity commented on src/NftEscrow.sol
> +    function unlock(IERC6909 source, uint256 tokenId, address to) external auth {
How do you know what value to use for `to` ?

2024-10-28 06:48 UTC, lemunozm commented on src/Portfolio.sol
> +    }
Yeah, we have talked and I finally understood the reasons. 

Nevertheless, the `file` method is a bit special because, AFAIK, it will be always called directly by an account. So, no contracts will call it, and no interface is needed theoretically. It's something we should add in most of our contract, but it does not nothing to do with the contract itself. 

In case we really need an interface, does it make sense to move it to its own `IFile`? I think so

2024-10-28 06:50 UTC, lemunozm commented on src/interfaces/Common.sol
> +interface IERC6909 {
Have you checked the note (line 4)?

2024-10-28 06:51 UTC, lemunozm commented on src/interfaces/IPortfolio.sol
> +        /// @notice Valuation used for this item.
Do you mean `IERC7726 valuation`? Why an address?

2024-10-28 06:53 UTC, lemunozm commented on src/libraries/MathLib.sol
> +            revert("MathLib/int128-overflow");
I was following the file style for MathLib. I agree we should use custom error. Nevertheless, I would say it's out of scope to do this in this PR. But we can do in a following one

2024-10-28 07:00 UTC, lemunozm commented on src/Portfolio.sol
> +        uint256 uniqueItemId = uint256(poolId) << 64 + itemId;
- I tested, and `uint256(poolId) << 64 + itemId` is enough without the parenthesis. The shift is first done over the `uint256(poolId)`.

- Agree, `encodePacked` seems more elegant. 26 gas is deprecable, I guess. Good suggestion.

- Right, I'm shifting 64 when only 32 are needed. Will go with `encodePacked` anyways

2024-10-28 07:01 UTC, lemunozm commented on src/Portfolio.sol
> +struct Item {
Why? This type is not used in the interface, only by the implementation.

2024-10-28 07:02 UTC, lemunozm commented on src/Portfolio.sol
> +    uint160 collateralId;
Shouldn't

2024-10-28 07:05 UTC, lemunozm commented on src/Portfolio.sol
> +    function create(uint64 poolId, ItemInfo calldata info, IERC6909 source, uint256 tokenId) external auth {
You're creating an underlying `Item`, note that `ItemInfo` is just another parameter used to create the internal `Item` with extra information.

2024-10-28 07:06 UTC, lemunozm commented on src/NftEscrow.sol
> +    function unlock(IERC6909 source, uint256 tokenId, address to) external auth {
It can be whatever, the upper layer through `auth` will handle that. Usually it will be the same who called lock() or some allowed account by them.

2024-10-28 12:19 UTC, wischli commented on src/libraries/MathLib.sol
> +            revert("MathLib/int128-overflow");
Agreeing with @lemunozm. Happy to create an issue for the custom error migration of MathLib and potentially other reused libs.

2024-10-28 13:06 UTC, lemunozm commented on src/Portfolio.sol
> +    }
Added the interface, which I think it makes sense: https://github.com/centrifuge/asset-pools/pull/24

2024-10-29 08:11 UTC, lemunozm commented on test/unit/Portfolio.t.sol
> +        );
This is why I think the interaction against `LinearAccrual` should be done only by one interface method called `getAccRate()` instead of `increase/decrease (aka modify) /renormalize...`. [Thread](https://kflabs.slack.com/archives/C07PG2EUR9C/p1728631897006459). It is very difficult to mock `LinearAccrual` and know what's happening in those lines. And this kind of lines appears in all test cases.

Note that although integration tests are something that helps here, we need unitary tests anyways to check easily all the combinatory produced by increase/decrease with principal,interests,price changes,...

Maybe something we can discuss in the offsite @wischli @ilinzweilin @hieronx

2024-10-29 08:47 UTC, lemunozm commented on test/unit/Portfolio.t.sol
> +        );
I left some a doc showing the approaches: https://www.notion.so/Minimize-LinearAccrual-interactions-12e2eac24e1780b79784f49004fd6f43

2024-10-29 09:20 UTC, wischli commented on test/unit/Portfolio.t.sol
> +        );
Thanks for the great doc @lemunozm! I hope we can find consensus before the offsite to get some PRs closed and have more capacity for other open questions. Personally, I am in favor of option B. Nevertheless, I believe this should be done in a separate PR after merging #9 when everyone is happy.

2024-10-29 09:40 UTC, lemunozm commented on test/unit/Portfolio.t.sol
> +        );
Fully agree, in case of doing it, to do in a new PR

2024-10-30 09:13 UTC, lemunozm commented on src/Portfolio.sol
> +    function decreasePrincipalDebt(uint64 poolId, uint32 itemId, uint128 principal) public auth {
Does it make sense for you to use the term "face value" instead of "principal" here? @hieronx @mustermeiszer 

I ask this because it seems that principal is used only for what we called loans/internal pricing, not for external pricing items. Maybe "FaceValue" is a more generic term for this.

2024-11-07 09:43 UTC, peculiarity commented on src/interfaces/IPortfolio.sol
> +        /// @notice Valuation used for this item.
Discard this

2024-11-07 10:11 UTC, peculiarity commented on src/Portfolio.sol
> +struct Item {
This is the approach we used in LPs but frankly I think that it shouldn't be there. @hieronx  can elaborate more.
In general it is a best practice to define structs in contracts because structs are used to organize data ( sometimes only for gas optimization only ) and interfaces just defines the behavior of the contract. 
The think is that we have to agree on a common approach and not have different ways of doing the same thing.

2024-11-07 10:12 UTC, peculiarity commented on src/Portfolio.sol
> +    uint160 collateralId;
I think the question was related to the `isValue` field. If `collateralId` is `0` can we assume that it just doesn't exist hence do we need the `isValid` flag at all? I might be missing something though.

2024-11-07 10:27 UTC, lemunozm commented on src/Portfolio.sol
> +struct Item {
I think interfaces should have as little information as possible. More information means more friction with the consumers of those interfaces. So, if they are minimal, we minimize the coupling between entities. 

I think this aligns with good developing practices, but open to listen other arguments

2024-11-11 09:06 UTC, lemunozm commented
Closed because now the source of truth will be the Accounting contract. 

Probably most of the code can be rescued to build the Bonds contract

2024-11-11 09:06 UTC, closed without merging